#define JX_JSON_ERROR                           1
#define JX_JSON_EOI                             2
#define JX_JSON_SEMICOLON                       3
#define JX_JSON_OPEN_CURLY_BRACE                4
#define JX_JSON_CLOSE_CURLY_BRACE               5
#define JX_JSON_COLON                           6
#define JX_JSON_COMMA                           7
#define JX_JSON_OPEN_RECT_BRACE                 8
#define JX_JSON_CLOSE_RECT_BRACE                9
#define JX_JSON_ICON                           10
#define JX_JSON_FCON                           11
#define JX_JSON_SCON                           12
#define JX_JSON_IDENT                          13
#define JX_JSON_TRUE                           14
#define JX_JSON_FALSE                          15
#define JX_JSON_NULL                           16
