#define JX_JXON_ERROR                           1
#define JX_JXON_EOI                             2
#define JX_JXON_SEMICOLON                       3
#define JX_JXON_OPEN_CURLY_BRACE                4
#define JX_JXON_CLOSE_CURLY_BRACE               5
#define JX_JXON_COLON                           6
#define JX_JXON_COMMA                           7
#define JX_JXON_OPEN_RECT_BRACE                 8
#define JX_JXON_CLOSE_RECT_BRACE                9
#define JX_JXON_OPEN_PAR                       10
#define JX_JXON_CLOSE_PAR                      11
#define JX_JXON_BUILTIN                        12
#define JX_JXON_ICON                           13
#define JX_JXON_FCON                           14
#define JX_JXON_SCON                           15
#define JX_JXON_IDENT                          16
#define JX_JXON_TRUE                           17
#define JX_JXON_FALSE                          18
#define JX_JXON_NULL                           19
#define JX_JXON_JUMP_REL                       20
#define JX_JXON_BREAK                          21
#define JX_JXON_CONTINUE                       22
#define JX_JXON_RETURN                         23
#define JX_JXON_TAIL_CALL                      24
