
/* Generated by re2c 0.12.3 on Wed Jul  8 17:31:20 2009 */
#line 1 "jx_jxon_scan.re"

/* RE2C-based tokenizer */


/* 
Copyright (c) 2009, DeLano Scientific LLC, Palo Alto, California, USA.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in the
 documentation and/or other materials provided with the distribution.

* Neither the name of the DeLano Scientific LLC nor the names of its
 contributors may be used to endorse or promote products derived from
 this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "jx_jxon_private.h"

#define JX_JXON_SCANNER_MODE_FILE          0
#define JX_JXON_SCANNER_MODE_STRING        1
#define JX_JXON_SCANNER_MODE_CONSOLE       2

typedef struct {
  jx_char *bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
  jx_int line;
  jx_int n_tok_parsed;

  jx_int mode, flags;
  FILE *file;
  jx_jxon_parse_context context;
  jx_ob saved_token;
  jx_int saved_token_type;
} jx_jxon_scanner_state;

#ifndef true
#define true 1
#endif

#ifndef false
#define false 0
#endif

#define   BSIZE   8192

#define   YYCTYPE     jx_char
#define   YYCURSOR    cursor
#define   YYLIMIT     s->lim
#define   YYMARKER    s->ptr
#define   YYFILL(n)   {cursor = jx_fill(s, cursor);}

#define   RET(i)   {s->cur = cursor; return i;}


/* parser allocator */

static void *jx__jxon_alloc(jx_size bytes)
{
  jx_char *ptr = NULL;
  ptr = jx_calloc(1, bytes);
  return (void *) ptr;
}

static void jx__jxon_free(void *ptr)
{
  if(ptr)
    jx_free(ptr);
}

static jx_size jx_read_file(FILE * file, jx_char * buf, jx_size buf_size, jx_int mode)
{
  switch (mode) {
  case JX_JXON_SCANNER_MODE_FILE:
    return fread((char *) buf, 1, buf_size, file);
    break;
  case JX_JXON_SCANNER_MODE_CONSOLE:
    if(fgets((char *) buf, buf_size, file)) {
      return jx_strlen(buf);
    } else
      return 0;
    break;
  }
  return 0;
}

static jx_char *jx_fill(jx_jxon_scanner_state * s, jx_char * cursor)
{
  switch (s->mode) {
  case JX_JXON_SCANNER_MODE_FILE:
  case JX_JXON_SCANNER_MODE_CONSOLE:
    if(!s->eof) {               /* only fill if eof is not set (known) */
      jx_diff cnt = s->tok - s->bot;    /* amount of open space in buffer */
      if(cnt) {
        if(s->lim > s->tok) {   /* any remaining characters? */
          jx_os_memcpy(s->bot, s->tok, s->lim - s->tok);        /* move to start of buffer */
        }
        s->tok = s->bot;        /* shift pointers accordingly */
        s->ptr -= cnt;
        cursor -= cnt;
        s->pos -= cnt;
        s->lim -= cnt;
      }
      if((s->top - s->lim) < BSIZE) {   /* open space less than read quantum? */
        /* allocate a larger buffer */
        jx_char *buf = (jx_char *) jx_calloc(1, ((s->lim - s->bot) +
                                                 BSIZE) * sizeof(jx_char));
        if(buf) {               /* and copy contents to new buffer */
          jx_os_memcpy(buf, s->tok, s->lim - s->tok);
          s->tok = buf;         /* adjust pointers accordingly */
          s->ptr = &buf[s->ptr - s->bot];
          cursor = &buf[cursor - s->bot];
          s->pos = &buf[s->pos - s->bot];
          s->lim = &buf[s->lim - s->bot];
          s->top = &s->lim[BSIZE];
          if(s->bot) {          /* free old buffer (if exists) */
            jx_free(s->bot);
          }
          s->bot = buf;         /* use the new buffer from now on */
        }
      }
      if((s->top - s->lim) < BSIZE) {
        /* unhandled error condition */
      } else {
        cnt = jx_read_file(s->file, s->lim, BSIZE, s->mode);
        if(cnt != BSIZE) {
          jx_size cc = cnt;
          while(cc < BSIZE) {
            s->lim[cc] = 0;
            cc++;
          }
          s->eof = &s->lim[cnt];
          if(cnt) {             /* short read ...there may be more to come */
            s->eof++;
          } else {              /* nothing read, so set the null sentinel */
            *(s->eof) = 0;
          }
        }
        s->lim += cnt;
      }
    }
    break;
  }
  return cursor;
}

static int jx_scan(jx_jxon_scanner_state * s)
{
  jx_char *cursor = s->cur;
std:
  s->tok = cursor;

#line 173 "<stdout>"
  {
    YYCTYPE yych;
    unsigned int yyaccept = 0;

    if((YYLIMIT - YYCURSOR) < 12)
      YYFILL(12);
    yych = *YYCURSOR;
    switch (yych) {
    case 0x00:
      goto yy41;
    case 0x09:
    case 0x0B:
    case 0x0C:
    case ' ':
      goto yy35;
    case 0x0A:
      goto yy39;
    case '"':
      goto yy9;
    case '#':
      goto yy37;
    case '(':
      goto yy19;
    case ')':
      goto yy21;
    case '+':
    case '-':
      goto yy2;
    case ',':
      goto yy23;
    case '.':
      goto yy7;
    case '0':
      goto yy4;
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy6;
    case ':':
      goto yy25;
    case ';':
      goto yy33;
    case '@':
      goto yy32;
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'G':
    case 'H':
    case 'I':
    case 'J':
    case 'K':
    case 'L':
    case 'M':
    case 'N':
    case 'O':
    case 'P':
    case 'Q':
    case 'R':
    case 'S':
    case 'T':
    case 'U':
    case 'V':
    case 'W':
    case 'X':
    case 'Y':
    case 'Z':
    case '_':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'g':
    case 'h':
    case 'i':
    case 'j':
    case 'k':
    case 'l':
    case 'm':
    case 'o':
    case 'p':
    case 'q':
    case 'r':
    case 's':
    case 'u':
    case 'v':
    case 'w':
    case 'x':
    case 'y':
    case 'z':
      goto yy31;
    case '[':
      goto yy11;
    case ']':
      goto yy13;
    case '`':
      goto yy10;
    case 'f':
      goto yy29;
    case 'n':
      goto yy30;
    case 't':
      goto yy27;
    case '{':
      goto yy15;
    case '}':
      goto yy17;
    default:
      goto yy43;
    }
  yy2:
    yyaccept = 0;
    yych = *(YYMARKER = ++YYCURSOR);
    switch (yych) {
    case '.':
      goto yy173;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy147;
    default:
      goto yy3;
    }
  yy3:
#line 238 "jx_jxon_scan.re"
    {
#ifdef JX_JXON_PARSER_DEBUG
      printf("unexpected character: %c\n", *s->tok);
#endif
      RET(JX_JXON_ERROR);
    }
#line 293 "<stdout>"
  yy4:
    yyaccept = 1;
    yych = *(YYMARKER = ++YYCURSOR);
    switch (yych) {
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy145;
    case 'X':
    case 'x':
      goto yy166;
    default:
      goto yy165;
    }
  yy5:
#line 210 "jx_jxon_scan.re"
    {
      RET(JX_JXON_ICON);
    }
#line 309 "<stdout>"
  yy6:
    yyaccept = 1;
    yych = *(YYMARKER = ++YYCURSOR);
    goto yy148;
  yy7:
    ++YYCURSOR;
    switch ((yych = *YYCURSOR)) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy137;
    default:
      goto yy8;
    }
  yy8:
#line 206 "jx_jxon_scan.re"
    {
      RET(JX_JXON_IDENT);
    }
#line 332 "<stdout>"
  yy9:
    yyaccept = 0;
    yych = *(YYMARKER = ++YYCURSOR);
    switch (yych) {
    case 0x00:
    case 0x0A:
      goto yy3;
    default:
      goto yy128;
    }
  yy10:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case ':':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'G':
    case 'H':
    case 'I':
    case 'J':
    case 'K':
    case 'L':
    case 'M':
    case 'N':
    case 'O':
    case 'P':
    case 'Q':
    case 'R':
    case 'S':
    case 'T':
    case 'U':
    case 'V':
    case 'W':
    case 'X':
    case 'Y':
    case 'Z':
    case '_':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
    case 'g':
    case 'h':
    case 'i':
    case 'j':
    case 'k':
    case 'l':
    case 'm':
    case 'n':
    case 'o':
    case 'p':
    case 'q':
    case 'r':
    case 's':
    case 't':
    case 'u':
    case 'v':
    case 'w':
    case 'x':
    case 'y':
    case 'z':
      goto yy124;
    default:
      goto yy3;
    }
  yy11:
    ++YYCURSOR;
#line 191 "jx_jxon_scan.re"
    {
      RET(JX_JXON_OPEN_RECT_BRACE);
    }
#line 414 "<stdout>"
  yy13:
    ++YYCURSOR;
#line 192 "jx_jxon_scan.re"
    {
      RET(JX_JXON_CLOSE_RECT_BRACE);
    }
#line 419 "<stdout>"
  yy15:
    ++YYCURSOR;
#line 194 "jx_jxon_scan.re"
    {
      RET(JX_JXON_OPEN_CURLY_BRACE);
    }
#line 424 "<stdout>"
  yy17:
    ++YYCURSOR;
#line 195 "jx_jxon_scan.re"
    {
      RET(JX_JXON_CLOSE_CURLY_BRACE);
    }
#line 429 "<stdout>"
  yy19:
    ++YYCURSOR;
#line 197 "jx_jxon_scan.re"
    {
      RET(JX_JXON_OPEN_PAR);
    }
#line 434 "<stdout>"
  yy21:
    ++YYCURSOR;
#line 198 "jx_jxon_scan.re"
    {
      RET(JX_JXON_CLOSE_PAR);
    }
#line 439 "<stdout>"
  yy23:
    ++YYCURSOR;
#line 200 "jx_jxon_scan.re"
    {
      RET(JX_JXON_COMMA);
    }
#line 444 "<stdout>"
  yy25:
    ++YYCURSOR;
#line 201 "jx_jxon_scan.re"
    {
      RET(JX_JXON_COLON);
    }
#line 449 "<stdout>"
  yy27:
    ++YYCURSOR;
    switch ((yych = *YYCURSOR)) {
    case 'r':
      goto yy120;
    default:
      goto yy106;
    }
  yy28:
#line 208 "jx_jxon_scan.re"
    {
      RET(JX_JXON_IDENT);
    }
#line 459 "<stdout>"
  yy29:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'a':
      goto yy115;
    default:
      goto yy106;
    }
  yy30:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'u':
      goto yy111;
    default:
      goto yy106;
    }
  yy31:
    yych = *++YYCURSOR;
    goto yy106;
  yy32:
    yyaccept = 0;
    yych = *(YYMARKER = ++YYCURSOR);
    switch (yych) {
    case '+':
    case '-':
    case '[':
      goto yy51;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy52;
    case 'B':
      goto yy50;
    case 'C':
      goto yy49;
    case 'R':
      goto yy48;
    case 'T':
      goto yy46;
    default:
      goto yy3;
    }
  yy33:
    ++YYCURSOR;
#line 220 "jx_jxon_scan.re"
    {
      RET(JX_JXON_SEMICOLON);
    }
#line 502 "<stdout>"
  yy35:
    ++YYCURSOR;
    yych = *YYCURSOR;
    goto yy45;
  yy36:
#line 223 "jx_jxon_scan.re"
    {
      goto std;
    }
#line 510 "<stdout>"
  yy37:
    ++YYCURSOR;
#line 225 "jx_jxon_scan.re"
    {
      goto comment;
    }
#line 515 "<stdout>"
  yy39:
    ++YYCURSOR;
#line 227 "jx_jxon_scan.re"
    {
      s->pos = cursor;
      s->line++;
      s->eof = NULL;
      goto std;
    }
#line 524 "<stdout>"
  yy41:
    ++YYCURSOR;
#line 233 "jx_jxon_scan.re"
    {
      if(cursor == s->eof)
        RET(JX_JXON_EOI);
      RET(JX_JXON_EOI);
    }
#line 532 "<stdout>"
  yy43:
    yych = *++YYCURSOR;
    goto yy3;
  yy44:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
  yy45:
    switch (yych) {
    case 0x09:
    case 0x0B:
    case 0x0C:
    case ' ':
      goto yy44;
    default:
      goto yy36;
    }
  yy46:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'A':
      goto yy91;
    default:
      goto yy47;
    }
  yy47:
    YYCURSOR = YYMARKER;
    switch (yyaccept) {
    case 0:
      goto yy3;
    case 1:
      goto yy5;
    case 2:
      goto yy28;
    case 3:
      goto yy139;
    }
  yy48:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'E':
      goto yy80;
    default:
      goto yy47;
    }
  yy49:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'O':
      goto yy67;
    default:
      goto yy47;
    }
  yy50:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'R':
      goto yy57;
    default:
      goto yy47;
    }
  yy51:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy52;
    default:
      goto yy47;
    }
  yy52:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy52;
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy55;
    default:
      goto yy54;
    }
  yy54:
#line 212 "jx_jxon_scan.re"
    {
      RET(JX_JXON_JUMP_REL);
    }
#line 619 "<stdout>"
  yy55:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy55;
    default:
      goto yy54;
    }
  yy57:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'E':
      goto yy58;
    default:
      goto yy47;
    }
  yy58:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'A':
      goto yy59;
    default:
      goto yy47;
    }
  yy59:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'K':
      goto yy60;
    default:
      goto yy47;
    }
  yy60:
    yych = *++YYCURSOR;
    switch (yych) {
    case '+':
    case '-':
    case '[':
      goto yy61;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy62;
    default:
      goto yy47;
    }
  yy61:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy62;
    default:
      goto yy47;
    }
  yy62:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy62;
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy65;
    default:
      goto yy64;
    }
  yy64:
#line 214 "jx_jxon_scan.re"
    {
      RET(JX_JXON_BREAK);
    }
#line 706 "<stdout>"
  yy65:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy65;
    default:
      goto yy64;
    }
  yy67:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'N':
      goto yy68;
    default:
      goto yy47;
    }
  yy68:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'T':
      goto yy69;
    default:
      goto yy47;
    }
  yy69:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'I':
      goto yy70;
    default:
      goto yy47;
    }
  yy70:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'N':
      goto yy71;
    default:
      goto yy47;
    }
  yy71:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'U':
      goto yy72;
    default:
      goto yy47;
    }
  yy72:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'E':
      goto yy73;
    default:
      goto yy47;
    }
  yy73:
    yych = *++YYCURSOR;
    switch (yych) {
    case '+':
    case '-':
    case '[':
      goto yy74;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy75;
    default:
      goto yy47;
    }
  yy74:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy75;
    default:
      goto yy47;
    }
  yy75:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy75;
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy78;
    default:
      goto yy77;
    }
  yy77:
#line 215 "jx_jxon_scan.re"
    {
      RET(JX_JXON_CONTINUE);
    }
#line 811 "<stdout>"
  yy78:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy78;
    default:
      goto yy77;
    }
  yy80:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'T':
      goto yy81;
    default:
      goto yy47;
    }
  yy81:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'U':
      goto yy82;
    default:
      goto yy47;
    }
  yy82:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'R':
      goto yy83;
    default:
      goto yy47;
    }
  yy83:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'N':
      goto yy84;
    default:
      goto yy47;
    }
  yy84:
    yych = *++YYCURSOR;
    switch (yych) {
    case '+':
    case '-':
    case '[':
      goto yy85;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy86;
    default:
      goto yy47;
    }
  yy85:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy86;
    default:
      goto yy47;
    }
  yy86:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy86;
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy89;
    default:
      goto yy88;
    }
  yy88:
#line 216 "jx_jxon_scan.re"
    {
      RET(JX_JXON_RETURN);
    }
#line 904 "<stdout>"
  yy89:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy89;
    default:
      goto yy88;
    }
  yy91:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'I':
      goto yy92;
    default:
      goto yy47;
    }
  yy92:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'L':
      goto yy93;
    default:
      goto yy47;
    }
  yy93:
    yych = *++YYCURSOR;
    switch (yych) {
    case '_':
      goto yy94;
    default:
      goto yy47;
    }
  yy94:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'C':
      goto yy95;
    default:
      goto yy47;
    }
  yy95:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'A':
      goto yy96;
    default:
      goto yy47;
    }
  yy96:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'L':
      goto yy97;
    default:
      goto yy47;
    }
  yy97:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'L':
      goto yy98;
    default:
      goto yy47;
    }
  yy98:
    yych = *++YYCURSOR;
    switch (yych) {
    case '+':
    case '-':
    case '[':
      goto yy99;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy100;
    default:
      goto yy47;
    }
  yy99:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy100;
    default:
      goto yy47;
    }
  yy100:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy100;
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy103;
    default:
      goto yy102;
    }
  yy102:
#line 218 "jx_jxon_scan.re"
    {
      RET(JX_JXON_TAIL_CALL);
    }
#line 1015 "<stdout>"
  yy103:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy103;
    default:
      goto yy102;
    }
  yy105:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
  yy106:
    switch (yych) {
    case '.':
      goto yy107;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'G':
    case 'H':
    case 'I':
    case 'J':
    case 'K':
    case 'L':
    case 'M':
    case 'N':
    case 'O':
    case 'P':
    case 'Q':
    case 'R':
    case 'S':
    case 'T':
    case 'U':
    case 'V':
    case 'W':
    case 'X':
    case 'Y':
    case 'Z':
    case '_':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
    case 'g':
    case 'h':
    case 'i':
    case 'j':
    case 'k':
    case 'l':
    case 'm':
    case 'n':
    case 'o':
    case 'p':
    case 'q':
    case 'r':
    case 's':
    case 't':
    case 'u':
    case 'v':
    case 'w':
    case 'x':
    case 'y':
    case 'z':
      goto yy105;
    default:
      goto yy28;
    }
  yy107:
    yyaccept = 2;
    YYMARKER = ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '.':
      goto yy108;
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'G':
    case 'H':
    case 'I':
    case 'J':
    case 'K':
    case 'L':
    case 'M':
    case 'N':
    case 'O':
    case 'P':
    case 'Q':
    case 'R':
    case 'S':
    case 'T':
    case 'U':
    case 'V':
    case 'W':
    case 'X':
    case 'Y':
    case 'Z':
    case '_':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
    case 'g':
    case 'h':
    case 'i':
    case 'j':
    case 'k':
    case 'l':
    case 'm':
    case 'n':
    case 'o':
    case 'p':
    case 'q':
    case 'r':
    case 's':
    case 't':
    case 'u':
    case 'v':
    case 'w':
    case 'x':
    case 'y':
    case 'z':
      goto yy109;
    default:
      goto yy28;
    }
  yy108:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'G':
    case 'H':
    case 'I':
    case 'J':
    case 'K':
    case 'L':
    case 'M':
    case 'N':
    case 'O':
    case 'P':
    case 'Q':
    case 'R':
    case 'S':
    case 'T':
    case 'U':
    case 'V':
    case 'W':
    case 'X':
    case 'Y':
    case 'Z':
    case '_':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
    case 'g':
    case 'h':
    case 'i':
    case 'j':
    case 'k':
    case 'l':
    case 'm':
    case 'n':
    case 'o':
    case 'p':
    case 'q':
    case 'r':
    case 's':
    case 't':
    case 'u':
    case 'v':
    case 'w':
    case 'x':
    case 'y':
    case 'z':
      goto yy109;
    default:
      goto yy47;
    }
  yy109:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '.':
      goto yy107;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'G':
    case 'H':
    case 'I':
    case 'J':
    case 'K':
    case 'L':
    case 'M':
    case 'N':
    case 'O':
    case 'P':
    case 'Q':
    case 'R':
    case 'S':
    case 'T':
    case 'U':
    case 'V':
    case 'W':
    case 'X':
    case 'Y':
    case 'Z':
    case '_':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
    case 'g':
    case 'h':
    case 'i':
    case 'j':
    case 'k':
    case 'l':
    case 'm':
    case 'n':
    case 'o':
    case 'p':
    case 'q':
    case 'r':
    case 's':
    case 't':
    case 'u':
    case 'v':
    case 'w':
    case 'x':
    case 'y':
    case 'z':
      goto yy109;
    default:
      goto yy28;
    }
  yy111:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'l':
      goto yy112;
    default:
      goto yy106;
    }
  yy112:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'l':
      goto yy113;
    default:
      goto yy106;
    }
  yy113:
    ++YYCURSOR;
    switch ((yych = *YYCURSOR)) {
    case '.':
      goto yy107;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'G':
    case 'H':
    case 'I':
    case 'J':
    case 'K':
    case 'L':
    case 'M':
    case 'N':
    case 'O':
    case 'P':
    case 'Q':
    case 'R':
    case 'S':
    case 'T':
    case 'U':
    case 'V':
    case 'W':
    case 'X':
    case 'Y':
    case 'Z':
    case '_':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
    case 'g':
    case 'h':
    case 'i':
    case 'j':
    case 'k':
    case 'l':
    case 'm':
    case 'n':
    case 'o':
    case 'p':
    case 'q':
    case 'r':
    case 's':
    case 't':
    case 'u':
    case 'v':
    case 'w':
    case 'x':
    case 'y':
    case 'z':
      goto yy105;
    default:
      goto yy114;
    }
  yy114:
#line 204 "jx_jxon_scan.re"
    {
      RET(JX_JXON_NULL);
    }
#line 1376 "<stdout>"
  yy115:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'l':
      goto yy116;
    default:
      goto yy106;
    }
  yy116:
    yych = *++YYCURSOR;
    switch (yych) {
    case 's':
      goto yy117;
    default:
      goto yy106;
    }
  yy117:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'e':
      goto yy118;
    default:
      goto yy106;
    }
  yy118:
    ++YYCURSOR;
    switch ((yych = *YYCURSOR)) {
    case '.':
      goto yy107;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'G':
    case 'H':
    case 'I':
    case 'J':
    case 'K':
    case 'L':
    case 'M':
    case 'N':
    case 'O':
    case 'P':
    case 'Q':
    case 'R':
    case 'S':
    case 'T':
    case 'U':
    case 'V':
    case 'W':
    case 'X':
    case 'Y':
    case 'Z':
    case '_':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
    case 'g':
    case 'h':
    case 'i':
    case 'j':
    case 'k':
    case 'l':
    case 'm':
    case 'n':
    case 'o':
    case 'p':
    case 'q':
    case 'r':
    case 's':
    case 't':
    case 'u':
    case 'v':
    case 'w':
    case 'x':
    case 'y':
    case 'z':
      goto yy105;
    default:
      goto yy119;
    }
  yy119:
#line 203 "jx_jxon_scan.re"
    {
      RET(JX_JXON_FALSE);
    }
#line 1467 "<stdout>"
  yy120:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'u':
      goto yy121;
    default:
      goto yy106;
    }
  yy121:
    yych = *++YYCURSOR;
    switch (yych) {
    case 'e':
      goto yy122;
    default:
      goto yy106;
    }
  yy122:
    ++YYCURSOR;
    switch ((yych = *YYCURSOR)) {
    case '.':
      goto yy107;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'G':
    case 'H':
    case 'I':
    case 'J':
    case 'K':
    case 'L':
    case 'M':
    case 'N':
    case 'O':
    case 'P':
    case 'Q':
    case 'R':
    case 'S':
    case 'T':
    case 'U':
    case 'V':
    case 'W':
    case 'X':
    case 'Y':
    case 'Z':
    case '_':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
    case 'g':
    case 'h':
    case 'i':
    case 'j':
    case 'k':
    case 'l':
    case 'm':
    case 'n':
    case 'o':
    case 'p':
    case 'q':
    case 'r':
    case 's':
    case 't':
    case 'u':
    case 'v':
    case 'w':
    case 'x':
    case 'y':
    case 'z':
      goto yy105;
    default:
      goto yy123;
    }
  yy123:
#line 202 "jx_jxon_scan.re"
    {
      RET(JX_JXON_TRUE);
    }
#line 1552 "<stdout>"
  yy124:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case ':':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'G':
    case 'H':
    case 'I':
    case 'J':
    case 'K':
    case 'L':
    case 'M':
    case 'N':
    case 'O':
    case 'P':
    case 'Q':
    case 'R':
    case 'S':
    case 'T':
    case 'U':
    case 'V':
    case 'W':
    case 'X':
    case 'Y':
    case 'Z':
    case '_':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
    case 'g':
    case 'h':
    case 'i':
    case 'j':
    case 'k':
    case 'l':
    case 'm':
    case 'n':
    case 'o':
    case 'p':
    case 'q':
    case 'r':
    case 's':
    case 't':
    case 'u':
    case 'v':
    case 'w':
    case 'x':
    case 'y':
    case 'z':
      goto yy124;
    default:
      goto yy126;
    }
  yy126:
#line 188 "jx_jxon_scan.re"
    {
      RET(JX_JXON_BUILTIN);
    }
#line 1627 "<stdout>"
  yy127:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
  yy128:
    switch (yych) {
    case 0x00:
    case 0x0A:
      goto yy47;
    case '"':
      goto yy130;
    case '\\':
      goto yy129;
    default:
      goto yy127;
    }
  yy129:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '"':
    case '\'':
    case '?':
    case '\\':
    case 'a':
    case 'b':
    case 'f':
    case 'n':
    case 'r':
    case 't':
    case 'v':
      goto yy127;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
      goto yy133;
    case 'x':
      goto yy132;
    default:
      goto yy47;
    }
  yy130:
    ++YYCURSOR;
#line 186 "jx_jxon_scan.re"
    {
      RET(JX_JXON_SCON);
    }
#line 1671 "<stdout>"
  yy132:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
      goto yy135;
    default:
      goto yy47;
    }
  yy133:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 0x00:
    case 0x0A:
      goto yy47;
    case '"':
      goto yy130;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
      goto yy133;
    case '\\':
      goto yy129;
    default:
      goto yy127;
    }
  yy135:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 0x00:
    case 0x0A:
      goto yy47;
    case '"':
      goto yy130;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
      goto yy135;
    case '\\':
      goto yy129;
    default:
      goto yy127;
    }
  yy137:
    yyaccept = 3;
    YYMARKER = ++YYCURSOR;
    if((YYLIMIT - YYCURSOR) < 3)
      YYFILL(3);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy137;
    case 'E':
    case 'e':
      goto yy140;
    case 'F':
    case 'L':
    case 'f':
    case 'l':
      goto yy141;
    default:
      goto yy139;
    }
  yy139:
#line 184 "jx_jxon_scan.re"
    {
      RET(JX_JXON_FCON);
    }
#line 1780 "<stdout>"
  yy140:
    yych = *++YYCURSOR;
    switch (yych) {
    case '+':
    case '-':
      goto yy142;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy143;
    default:
      goto yy47;
    }
  yy141:
    yych = *++YYCURSOR;
    goto yy139;
  yy142:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy143;
    default:
      goto yy47;
    }
  yy143:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy143;
    case 'F':
    case 'L':
    case 'f':
    case 'l':
      goto yy141;
    default:
      goto yy139;
    }
  yy145:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy145;
    default:
      goto yy5;
    }
  yy147:
    yyaccept = 1;
    YYMARKER = ++YYCURSOR;
    if((YYLIMIT - YYCURSOR) < 4)
      YYFILL(4);
    yych = *YYCURSOR;
  yy148:
    switch (yych) {
    case '.':
      goto yy149;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy147;
    case 'E':
    case 'e':
      goto yy150;
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy145;
    default:
      goto yy5;
    }
  yy149:
    yyaccept = 3;
    yych = *(YYMARKER = ++YYCURSOR);
    switch (yych) {
    case 'E':
    case 'e':
      goto yy156;
    default:
      goto yy155;
    }
  yy150:
    yych = *++YYCURSOR;
    switch (yych) {
    case '+':
    case '-':
      goto yy151;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy152;
    default:
      goto yy47;
    }
  yy151:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy152;
    default:
      goto yy47;
    }
  yy152:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy152;
    case 'F':
    case 'L':
    case 'f':
    case 'l':
      goto yy141;
    default:
      goto yy139;
    }
  yy154:
    yyaccept = 3;
    YYMARKER = ++YYCURSOR;
    if((YYLIMIT - YYCURSOR) < 3)
      YYFILL(3);
    yych = *YYCURSOR;
  yy155:
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy154;
    case 'E':
    case 'e':
      goto yy160;
    case 'F':
    case 'L':
    case 'f':
    case 'l':
      goto yy141;
    default:
      goto yy139;
    }
  yy156:
    yych = *++YYCURSOR;
    switch (yych) {
    case '+':
    case '-':
      goto yy157;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy158;
    default:
      goto yy47;
    }
  yy157:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy158;
    default:
      goto yy47;
    }
  yy158:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy158;
    case 'F':
    case 'L':
    case 'f':
    case 'l':
      goto yy141;
    default:
      goto yy139;
    }
  yy160:
    yych = *++YYCURSOR;
    switch (yych) {
    case '+':
    case '-':
      goto yy161;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy162;
    default:
      goto yy47;
    }
  yy161:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy162;
    default:
      goto yy47;
    }
  yy162:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy162;
    case 'F':
    case 'L':
    case 'f':
    case 'l':
      goto yy141;
    default:
      goto yy139;
    }
  yy164:
    yyaccept = 1;
    YYMARKER = ++YYCURSOR;
    if((YYLIMIT - YYCURSOR) < 4)
      YYFILL(4);
    yych = *YYCURSOR;
  yy165:
    switch (yych) {
    case '.':
      goto yy149;
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy164;
    case 'E':
    case 'e':
      goto yy150;
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy171;
    default:
      goto yy5;
    }
  yy166:
    yych = *++YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
      goto yy167;
    default:
      goto yy47;
    }
  yy167:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
    case 'A':
    case 'B':
    case 'C':
    case 'D':
    case 'E':
    case 'F':
    case 'a':
    case 'b':
    case 'c':
    case 'd':
    case 'e':
    case 'f':
      goto yy167;
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy169;
    default:
      goto yy5;
    }
  yy169:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy169;
    default:
      goto yy5;
    }
  yy171:
    ++YYCURSOR;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 'L':
    case 'U':
    case 'l':
    case 'u':
      goto yy171;
    default:
      goto yy5;
    }
  yy173:
    ++YYCURSOR;
    switch ((yych = *YYCURSOR)) {
    case '0':
    case '1':
    case '2':
    case '3':
    case '4':
    case '5':
    case '6':
    case '7':
    case '8':
    case '9':
      goto yy137;
    default:
      goto yy47;
    }
  }
#line 245 "jx_jxon_scan.re"

comment:

#line 2195 "<stdout>"
  {
    YYCTYPE yych;
    if(YYLIMIT == YYCURSOR)
      YYFILL(1);
    yych = *YYCURSOR;
    switch (yych) {
    case 0x00:
      goto yy176;
    case 0x0A:
      goto yy177;
    default:
      goto yy179;
    }
  yy176:
  yy177:
    ++YYCURSOR;
#line 250 "jx_jxon_scan.re"
    {
      if((s->flags & JX_SCANNER_FLAG_ECHO_COMMENTS) && (cursor > s->tok)) {
        fwrite(s->tok, (cursor - s->tok), 1, stdout);
      }
      s->pos = cursor;
      s->line++;
      s->eof = NULL;
      goto std;
    }
#line 2218 "<stdout>"
  yy179:
    ++YYCURSOR;
#line 261 "jx_jxon_scan.re"
    {
      goto comment;
    }
#line 2224 "<stdout>"
  }
#line 263 "jx_jxon_scan.re"

}


/* not used:

   "."         { RET(JX_JXON_DOT); }

   "`"         { RET(JX_JXON_BACKAPOSTROPHE); }

   (['] (ESC|any\[\n\\'])* [']) { RET(JX_JXON_SCON); }


   "<"         { RET(JX_JXON_LESS_THAN); }

   "<="        { RET(JX_JXON_LESS_THAN_OR_EQ); }

   ">"         { RET(JX_JXON_GREATER_THAN); }

   ">="        { RET(JX_JXON_GREATER_THAN_OR_EQ); }

   "-"         { RET(JX_JXON_MINUS); }

   "+"         { RET(JX_JXON_PLUS); }

   (['] (ESC|any\[\n\\'])* [']) { RET(JX_JXON_SCON); }


   "="         { RET(JX_JXON_EQUALS); }

 */
#define SSCANF_BUFSIZE 32


/* anticipated use cases:
   (1) parsing a string buffer from memory
   (2) parsing from a file or file descriptor (e.g. stdin) 
   (3) parsing from a character stream 
*/

static void jx_jxon_scan_input(jx_jxon_scanner_state * state)
{
  /* allocate parser */

  void *jx_Parser = jx_jxon_Alloc((void *(*)(size_t)) jx__jxon_alloc);
  jx_int tok_type = 0;
  jx_char stack_buffer[SSCANF_BUFSIZE];

  state->context.status = 0;
  state->n_tok_parsed = 0;

  if(state->saved_token_type) {
    state->n_tok_parsed++;
    jx_jxon_(jx_Parser, state->saved_token_type, state->saved_token, &state->context);
    state->saved_token_type = 0;

    state->saved_token = jx_ob_from_null();
  }
  while(!state->context.exhausted) {
    tok_type = jx_scan(state);
    {
      jx_ob token = JX_OB_NULL;
      jx_size st_len = state->cur - state->tok;
#ifdef JX_JXON_PARSER_DEBUG

      if(1) {
        jx_size i;
        jx_char *c = state->tok;

        if(st_len) {
          printf(" ");
          for(i = 0; i < st_len; i++) {
            printf("%c", *(c++));
          }
          printf("\n");
        }
      }
#endif

      switch (tok_type) {
      case JX_JXON_ICON:
      case JX_JXON_FCON:
      case JX_JXON_SCON:
      case JX_JXON_IDENT:
      case JX_JXON_JUMP_REL:
        {
          char *buffer = stack_buffer;
          if(st_len >= SSCANF_BUFSIZE) {
            buffer = jx_malloc(st_len + 1);
          }
          if(buffer) {
            jx_os_strncpy(buffer, state->tok, st_len);
            buffer[st_len] = 0;
            switch (tok_type) {
            case JX_JXON_JUMP_REL:
              {
#ifdef JX_64_BIT
                jx_int icon;
                if(jx_os_sscanf(buffer + 1, "%lli", &icon) != 1) {      /* use strtol instead? */
                  icon = 0;
                }
                token = jx_ob_from_int(icon);
#else
                int icon;
                if(jx_os_sscanf(buffer + 1, "%i", &icon) != 1) {        /* use strtol instead? */
                  icon = 0;
                }
#endif
                token = jx_ob_from_opcode(JX_OPCODE_JUMP_RELATIVE, icon);
              }
              break;
            case JX_JXON_ICON:
              {
#ifdef JX_64_BIT
                jx_int icon;
                if(jx_os_sscanf(buffer, "%lli", &icon) != 1) {  /* use strtol instead? */
                  icon = 0;
                }
                token = jx_ob_from_int(icon);
#else
                int icon;
                if(jx_os_sscanf(buffer, "%i", &icon) != 1) {    /* use strtol instead? */
                  icon = 0;
                }
#endif
                token = jx_ob_from_int(icon);
              }
              break;
            case JX_JXON_FCON:
              {
#ifdef JX_64_BIT
                double fcon;
                if(jx_os_sscanf(buffer, "%lf", &fcon) != 1) {   /* use strtof instead? */
                  fcon = 0.0;
                }
#else
                float fcon;
                if(jx_os_sscanf(buffer, "%f", &fcon) != 1) {    /* use strtof instead? */
                  fcon = 0.0F;
                }
#endif
                token = jx_ob_from_float(fcon);
              }
              break;
            case JX_JXON_SCON:
              buffer[st_len - 1] = 0;
              token = jx_ob_from_str(buffer + 1);
              break;
            case JX_JXON_IDENT:
              token = jx_ob_from_ident(buffer);
              break;
            }
            if(buffer != stack_buffer)
              jx_free(buffer);
          }
          break;
      case JX_JXON_TRUE:
          token = jx_ob_from_bool(true);
          break;
      case JX_JXON_FALSE:
          token = jx_ob_from_bool(false);
          break;
      case JX_JXON_NULL:
          token = jx_ob_from_null();
          break;
      case JX_JXON_BREAK:
          token = jx_ob_from_opcode(JX_OPCODE_BREAK, 0);
          break;
      case JX_JXON_CONTINUE:
          token = jx_ob_from_opcode(JX_OPCODE_CONTINUE, 0);
          break;
      case JX_JXON_RETURN:
          token = jx_ob_from_opcode(JX_OPCODE_RETURN, 0);
          break;
      case JX_JXON_TAIL_CALL:
          token = jx_ob_from_opcode(JX_OPCODE_TAIL_CALL, 0);
          break;
      case JX_JXON_BUILTIN:
          token = jx_builtin_new_from_selector(0);
          break;
      case JX_JXON_OPEN_RECT_BRACE:
      case JX_JXON_CLOSE_RECT_BRACE:
      case JX_JXON_OPEN_CURLY_BRACE:
      case JX_JXON_CLOSE_CURLY_BRACE:
      case JX_JXON_COMMA:
      case JX_JXON_EOI:
      case JX_JXON_SEMICOLON:
          /* do nothing */
          break;
      case JX_JXON_ERROR:
          state->context.status = JX_STATUS_SYNTAX_ERROR;
          break;
        }
      }
      switch (tok_type) {
      case JX_JXON_SEMICOLON:
      case JX_JXON_EOI:
        if(state->saved_token_type) {
          state->saved_token = jx_ob_from_null();
          state->saved_token_type = 0;
        }
        break;
      default:
        state->saved_token_type = tok_type;
        state->saved_token = token;
        break;
      }
      jx_jxon_(jx_Parser, (int) tok_type, token, &state->context);

      if(!jx_ok(state->context.status)) {       /* something bad happened */
        state->saved_token = jx_ob_from_null();
        state->saved_token_type = 0;
        break;
      }

      switch (tok_type) {
      case JX_JXON_SEMICOLON:
      case JX_JXON_EOI:
        {                       /* parse a null token to enable acceptance */
          jx_ob ob = JX_OB_NULL;
          jx_jxon_(jx_Parser, 0, ob, &state->context);
        }
        break;
      }
      if(state->context.status) /* accepted or complete */
        break;
      else
        state->n_tok_parsed++;
    }
  }

  if(tok_type == JX_JXON_EOI) {
    state->context.exhausted = JX_TRUE;
  }

  /* free the parser instance */
  jx_jxon_Free(jx_Parser, jx__jxon_free);
}

static jx_status jx_jxon_scanner_state_init(jx_jxon_scanner_state * state)
{
  memset(state, 0, sizeof(jx_jxon_scanner_state));
  return JX_SUCCESS;
}

static jx_status jx_jxon_scanner_state_reset(jx_jxon_scanner_state * state)
{
  if(state->bot)
    jx_free(state->bot);
  state->bot = NULL;
  state->tok = NULL;
  state->ptr = NULL;
  state->cur = NULL;
  state->pos = NULL;
  state->lim = NULL;
  state->top = NULL;
  state->eof = NULL;
  state->line = 0;
  state->n_tok_parsed = 0;
  return JX_SUCCESS;
}

static jx_status jx_jxon_scanner_state_purge(jx_jxon_scanner_state * state)
{
  /* free last object */
  jx_ob_free(state->context.result);
  /* free saved token (if any) */
  jx_ob_free(state->saved_token);
  /* free the input buffer (if using stdin) */
  switch (state->mode) {
  case JX_JXON_SCANNER_MODE_FILE:
  case JX_JXON_SCANNER_MODE_CONSOLE:
    if(state->bot)
      jx_free(state->bot);
    break;
  }
  return JX_SUCCESS;
}

jx_ob jx_ob_from_jxon_str(jx_char * st)
{
  jx_jxon_scanner_state state;
  jx_jxon_scanner_state_init(&state);
  jx_ob result = JX_OB_NULL;
  state.cur = st;
  state.eof = st + jx_strlen(st) + 1;
  state.mode = JX_JXON_SCANNER_MODE_STRING;
  jx_jxon_scan_input(&state);
  if(state.context.status == JX_YES) {
    if(state.n_tok_parsed)      /* non-blank string? */
      result = state.context.result;
    state.context.result = jx_ob_from_null();
  }
  jx_jxon_scanner_state_purge(&state);
  return result;
}

void jx_jxon_echo_stdin(void)
{
  jx_jxon_scanner_state state;
  jx_jxon_scanner_state_init(&state);
  jx_bool done = JX_FALSE;
  while(!done) {
    jx_jxon_scan_input(&state);
    switch (state.context.status) {
    case JX_STATUS_SYNTAX_ERROR:
      printf("syntax error.\n");
      break;
    case JX_YES:               /* accepted */
      {
        jx_ob jxon = jx_ob_to_jxon(state.context.result);
        if(state.n_tok_parsed)
          printf("%s;\n", jx_ob_as_str(&jxon));
        jx_ob_free(jxon);
      }
      state.context.result = jx_null_with_ob(state.context.result);
      break;
    case JX_FAILURE:
      done = JX_TRUE;
      break;
    }
    if(state.context.exhausted)
      done = JX_TRUE;
  }
  jx_jxon_scanner_state_purge(&state);
}

#define JX_JXON_SCANNER_MAGIC "jxJSc"

typedef struct {
  jx_opaque_ob opaque;
  jx_jxon_scanner_state state;
} jx_jxon_scanner;

static jx_status jx_jxon_scanner_free(jx_jxon_scanner * scanner)
{
  jx_status result = JX_FAILURE;
  jx_ob magic = jx_ob_from_str(JX_JXON_SCANNER_MAGIC);
  if(jx_ob_equal(scanner->opaque.magic, magic)) {
    jx_jxon_scanner_state_purge(&scanner->state);
    jx_ob_free(scanner->opaque.magic);
    jx_free(scanner);
    result = JX_SUCCESS;
  }
  jx_ob_free(magic);
  return result;
}

jx_ob jx_jxon_scanner_new_with_file(FILE * file, jx_int flags)
{
  jx_ob result = JX_OB_NULL;
  jx_jxon_scanner *scanner = (jx_jxon_scanner *) jx_calloc(1, sizeof(jx_jxon_scanner));
  if(scanner) {
    if(jx_ok(jx_jxon_scanner_state_init(&scanner->state))) {
      scanner->opaque.magic = jx_ob_from_str(JX_JXON_SCANNER_MAGIC);
      scanner->opaque.free_fn = (jx_opaque_free_fn) jx_jxon_scanner_free;
      scanner->state.file = file;
      scanner->state.flags = flags;
      if(isatty((int) fileno(file))) {
        scanner->state.mode = JX_JXON_SCANNER_MODE_CONSOLE;
      } else {
        scanner->state.mode = JX_JXON_SCANNER_MODE_FILE;
      }
      result = jx_builtin_new_with_opaque_ob(&scanner->opaque);
    } else
      jx_free(scanner);
  }
  return result;
}

jx_ob jx_jxon_scanner_get_error_message(jx_ob scanner_ob)
{
  jx_ob result = jx_ob_from_null();
  jx_ob magic = jx_ob_from_str(JX_JXON_SCANNER_MAGIC);
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_jxon_scanner *scanner = (jx_jxon_scanner *) scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic, magic)) {
      jx_jxon_scanner_state *state = &scanner->state;
      jx_ob list = jx_list_new();
      if(JX_OK(state->context.status)) {
        jx_char buffer[50];
        sprintf(buffer, "Error: failure on or before line %d\n", (int) state->line + 1);
        jx_list_append(list, jx_ob_from_str(buffer));
      } else {
        jx_char buffer[50];
        sprintf(buffer, "Error: invalid syntax on line %d\n", (int) state->line + 1);
        jx_list_append(list, jx_ob_from_str(buffer));
      }
      if(state->bot != state->lim) {
        if(state->tok >= state->pos) {
          jx_list_append(list,
                         jx_ob_from_str_with_len(state->pos, state->tok - state->pos));
        } else if(state->tok > state->bot) {
          jx_list_append(list,
                         jx_ob_from_str_with_len(state->bot, state->tok - state->bot));
        }
        if((state->cur > state->tok) && state->tok && state->tok[0]) {
          jx_list_append(list, jx_ob_from_str(" -->"));
          jx_list_append(list,
                         jx_ob_from_str_with_len(state->tok, state->cur - state->tok));
          jx_list_append(list, jx_ob_from_str("<-- "));
          if(state->lim > state->cur) {
            jx_char *ch = state->cur;
            while((ch < state->lim) && (*ch != '\n') && (*ch != '\r'))
              ch++;
            jx_list_append(list, jx_ob_from_str_with_len(state->cur, ch - state->cur));
          }
        } else {
          jx_list_append(list, jx_ob_from_str("<-- (at end of input)"));
        }
      } else {
        jx_list_append(list, jx_ob_from_str("<-- (at end of input)"));
      }
      result = jx_str_join_with_list(list);
    }
  }
  jx_ob_free(magic);
  return result;
}

jx_status jx_jxon_scanner_next_ob(jx_ob * result, jx_ob scanner_ob)
{
  jx_ob magic = jx_ob_from_str(JX_JXON_SCANNER_MAGIC);
  jx_status status = JX_FAILURE;
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_jxon_scanner *scanner = (jx_jxon_scanner *) scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic, magic)) {
      jx_jxon_scanner_state *state = &scanner->state;
      state->context.status = JX_SUCCESS;
      while(!state->context.status) {
        jx_jxon_scan_input(state);
        switch (state->context.status) {
        case JX_YES:           /* accept called */
          jx_ob_replace(result, state->context.result);
          state->context.result = jx_ob_from_null();
          status = state->n_tok_parsed ? JX_YES : JX_NO;        /* but were any tokens parsed */
          break;
        default:
          status = state->context.status;
          break;
        }
        if(state->context.exhausted) {
          if(!status)
            status = JX_STATUS_EXHAUSTED;
          break;
        }
      }
    }
  }
  jx_ob_free(magic);
  return status;
}

jx_status jx_jxon_scanner_purge_input(jx_ob scanner_ob)
{
  jx_ob magic = jx_ob_from_str(JX_JXON_SCANNER_MAGIC);
  jx_status status = JX_FAILURE;
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_jxon_scanner *scanner = (jx_jxon_scanner *) scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic, magic)) {
      jx_jxon_scanner_state *state = &scanner->state;
      jx_jxon_scanner_state_reset(state);
      status = JX_SUCCESS;
    }
  }
  jx_ob_free(magic);
  return status;
}
