/* Generated by re2c 0.12.3 on Wed Jun  3 02:17:42 2009 */
#line 1 "jx_py_scan.re"
/* RE2C-based tokenizer */

/* 
Copyright (c) 2009, DeLano Scientific LLC, Palo Alto, California, USA.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in the
 documentation and/or other materials provided with the distribution.

* Neither the name of the DeLano Scientific LLC nor the names of its
 contributors may be used to endorse or promote products derived from
 this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "jx_py_private.h"

#define JX_PY_SCANNER_MODE_FILE    0 
#define JX_PY_SCANNER_MODE_STRING  1
#define JX_PY_SCANNER_MODE_CONSOLE 2

typedef struct {
  jx_char *bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
  jx_int line;
  jx_int n_tok_parsed;
  jx_int mode;
  FILE *file;
  jx_py_parse_context context;
  jx_ob indent_stack;
  jx_int current_indent;
  jx_bool newline_just_seen;
  jx_bool colon_just_seen;
  jx_bool saved_token;
} jx_py_scanner_state;

#ifndef true
#define true 1
#endif

#ifndef false
#define false 0
#endif

#define   BSIZE   8192

#define   YYCTYPE     jx_char
#define   YYCURSOR    cursor
#define   YYLIMIT     s->lim
#define   YYMARKER    s->ptr
#define   YYFILL(n)   {cursor = jx_fill(s, cursor);}

#define   RET(i)   {s->cur = cursor; return i;}

#ifndef JX_PY_EOI
#define JX_PY_EOI -1
#endif

#ifndef JX_PY_DEDENT_NEWLINE
#define JX_PY_DEDENT_NEWLINE -2
#endif

/* parser allocator */

static void *jx__py_alloc(jx_size bytes)
{
  jx_char *ptr = NULL;
  ptr = jx_calloc(1,bytes);
  return (void*)ptr;
}

static void jx__py_free(void *ptr)
{
  if(ptr) 
    jx_free(ptr);
}

static jx_size jx_read_file(FILE *file, jx_char *buf, jx_size buf_size, jx_int mode)
{
  switch(mode) {
  case JX_PY_SCANNER_MODE_FILE:
    return fread((char*)buf, 1, buf_size, file);
    break;
  case JX_PY_SCANNER_MODE_CONSOLE:
    if(fgets((char*)buf, buf_size, file)) {
      return jx_strlen(buf);
    } else 
      return 0;
    break;
  }
  return 0;
}

static jx_char *jx_fill(jx_py_scanner_state *s, jx_char *cursor)
{
  switch(s->mode) {
  case JX_PY_SCANNER_MODE_FILE:
  case JX_PY_SCANNER_MODE_CONSOLE:
    if(!s->eof) { /* only fill if eof is not set (known) */
      jx_diff cnt = s->tok - s->bot; /* amount of open space in buffer */
      if(cnt) {
        if(s->lim > s->tok) { /* any remaining characters? */
          jx_os_memcpy(s->bot, s->tok, s->lim - s->tok); /* move to start of buffer */
        }
        s->tok = s->bot;  /* shift pointers accordingly */
        s->ptr -= cnt; 
        cursor -= cnt;
        s->pos -= cnt;
        s->lim -= cnt;
      }
      if((s->top - s->lim) < BSIZE) { /* open space less than read quantum? */
        /* allocate a larger buffer */
        jx_char *buf = (jx_char*) jx_calloc(1,((s->lim - s->bot) +
                                               BSIZE)*sizeof(jx_char));
        if(buf) { /* and copy contents to new buffer */
          jx_os_memcpy(buf, s->tok, s->lim - s->tok);
          s->tok = buf; /* adjust pointers accordingly */
          s->ptr = &buf[s->ptr - s->bot];
          cursor = &buf[cursor - s->bot];
          s->pos = &buf[s->pos - s->bot];
          s->lim = &buf[s->lim - s->bot];
          s->top = &s->lim[BSIZE];
          if(s->bot) { /* free old buffer (if exists) */
            jx_free(s->bot);
          }
          s->bot = buf; /* use the new buffer from now on */
        }
      }
      if((s->top - s->lim) < BSIZE) {
        /* unhandled error condition */
      } else {
        cnt = jx_read_file(s->file, s->lim, BSIZE, s->mode);
        if(cnt != BSIZE) {
          jx_size cc = cnt;
          while(cc<BSIZE) {
            s->lim[cc] = 0;
            cc++;
          }
          s->eof = &s->lim[cnt]; 
          if(cnt) { /* short read ...there may be more to come */
            s->eof++; 
          } else { /* nothing read, so set the null sentinel */
            *(s->eof) = 0;
          }
        }
        s->lim += cnt;
      }
    }
    break;
  }
  return cursor;
}
  
static int jx_scan(jx_py_scanner_state *s)
{
  jx_char *cursor = s->cur;
 std:
  s->tok = cursor;
  
  
#line 182 "<stdout>"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:	goto yy63;
	case 0x09:
	case 0x0B:
	case 0x0C:
	case ' ':	goto yy57;
	case 0x0A:	goto yy61;
	case '!':	goto yy48;
	case '"':	goto yy17;
	case '#':	goto yy59;
	case '%':	goto yy42;
	case '\'':	goto yy18;
	case '(':	goto yy24;
	case ')':	goto yy26;
	case '*':	goto yy38;
	case '+':	goto yy34;
	case ',':	goto yy55;
	case '-':	goto yy36;
	case '.':	goto yy15;
	case '/':	goto yy40;
	case '0':	goto yy12;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy14;
	case ':':	goto yy51;
	case ';':	goto yy53;
	case '<':	goto yy44;
	case '=':	goto yy46;
	case '>':	goto yy49;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'o':
	case 'q':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy19;
	case '[':	goto yy20;
	case ']':	goto yy22;
	case 'd':	goto yy9;
	case 'e':	goto yy4;
	case 'f':	goto yy7;
	case 'i':	goto yy2;
	case 'l':	goto yy10;
	case 'n':	goto yy5;
	case 'p':	goto yy6;
	case 'r':	goto yy11;
	case 'w':	goto yy8;
	case '{':	goto yy28;
	case '}':	goto yy30;
	case '~':	goto yy32;
	default:	goto yy65;
	}
yy2:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'f':	goto yy190;
	case 'n':	goto yy192;
	default:	goto yy85;
	}
yy3:
#line 214 "jx_py_scan.re"
	{ RET(JX_PY_NAME); }
#line 295 "<stdout>"
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'l':	goto yy183;
	default:	goto yy85;
	}
yy5:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'o':	goto yy180;
	default:	goto yy85;
	}
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'a':	goto yy171;
	case 'r':	goto yy172;
	default:	goto yy85;
	}
yy7:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'o':	goto yy168;
	default:	goto yy85;
	}
yy8:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'h':	goto yy163;
	default:	goto yy85;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'e':	goto yy158;
	default:	goto yy85;
	}
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'a':	goto yy152;
	default:	goto yy85;
	}
yy11:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'e':	goto yy146;
	default:	goto yy85;
	}
yy12:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy122;
	case 'X':
	case 'x':	goto yy139;
	default:	goto yy138;
	}
yy13:
#line 206 "jx_py_scan.re"
	{ RET(JX_PY_ICON); }
#line 368 "<stdout>"
yy14:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy120;
yy15:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy110;
	default:	goto yy16;
	}
yy16:
#line 271 "jx_py_scan.re"
	{
#ifdef JX_PY_PARSER_DEBUG
      printf("unexpected character: %c\n", *s->tok);
#endif
       RET(JX_PY_ERROR);
    }
#line 396 "<stdout>"
yy17:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy16;
	default:	goto yy101;
	}
yy18:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy16;
	default:	goto yy91;
	}
yy19:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy85;
yy20:
	++YYCURSOR;
#line 216 "jx_py_scan.re"
	{ RET(JX_PY_OPEN_RECT_BRACE); }
#line 421 "<stdout>"
yy22:
	++YYCURSOR;
#line 217 "jx_py_scan.re"
	{ RET(JX_PY_CLOSE_RECT_BRACE); }
#line 426 "<stdout>"
yy24:
	++YYCURSOR;
#line 219 "jx_py_scan.re"
	{ RET(JX_PY_OPEN_PAR); }
#line 431 "<stdout>"
yy26:
	++YYCURSOR;
#line 220 "jx_py_scan.re"
	{ RET(JX_PY_CLOSE_PAR); }
#line 436 "<stdout>"
yy28:
	++YYCURSOR;
#line 222 "jx_py_scan.re"
	{ RET(JX_PY_OPEN_CURLY_BRACE); }
#line 441 "<stdout>"
yy30:
	++YYCURSOR;
#line 223 "jx_py_scan.re"
	{ RET(JX_PY_CLOSE_CURLY_BRACE); }
#line 446 "<stdout>"
yy32:
	++YYCURSOR;
#line 225 "jx_py_scan.re"
	{ RET(JX_PY_TILDE); }
#line 451 "<stdout>"
yy34:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy82;
	default:	goto yy35;
	}
yy35:
#line 226 "jx_py_scan.re"
	{ RET(JX_PY_PLUS); }
#line 461 "<stdout>"
yy36:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy80;
	default:	goto yy37;
	}
yy37:
#line 227 "jx_py_scan.re"
	{ RET(JX_PY_MINUS); }
#line 471 "<stdout>"
yy38:
	++YYCURSOR;
#line 229 "jx_py_scan.re"
	{ RET(JX_PY_ASTERISK); }
#line 476 "<stdout>"
yy40:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '/':	goto yy78;
	default:	goto yy41;
	}
yy41:
#line 230 "jx_py_scan.re"
	{ RET(JX_PY_SLASH); }
#line 486 "<stdout>"
yy42:
	++YYCURSOR;
#line 232 "jx_py_scan.re"
	{ RET(JX_PY_PERCENT); }
#line 491 "<stdout>"
yy44:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy76;
	case '>':	goto yy74;
	default:	goto yy45;
	}
yy45:
#line 234 "jx_py_scan.re"
	{ RET(JX_PY_LESS_THAN); }
#line 502 "<stdout>"
yy46:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy72;
	default:	goto yy47;
	}
yy47:
#line 242 "jx_py_scan.re"
	{ RET(JX_PY_EQUALS); }
#line 512 "<stdout>"
yy48:
	yych = *++YYCURSOR;
	switch(yych) {
	case '=':	goto yy70;
	default:	goto yy16;
	}
yy49:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy68;
	default:	goto yy50;
	}
yy50:
#line 239 "jx_py_scan.re"
	{ RET(JX_PY_GREATER_THAN); }
#line 528 "<stdout>"
yy51:
	++YYCURSOR;
#line 247 "jx_py_scan.re"
	{ RET(JX_PY_COLON); }
#line 533 "<stdout>"
yy53:
	++YYCURSOR;
#line 249 "jx_py_scan.re"
	{ RET(JX_PY_SEMICOLON); }
#line 538 "<stdout>"
yy55:
	++YYCURSOR;
#line 251 "jx_py_scan.re"
	{ RET(JX_PY_COMMA); }
#line 543 "<stdout>"
yy57:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy67;
yy58:
#line 253 "jx_py_scan.re"
	{ if(s->pos == s->tok) 
                    s->current_indent = cursor - s->pos;
                  goto std; }
#line 553 "<stdout>"
yy59:
	++YYCURSOR;
#line 257 "jx_py_scan.re"
	{ goto comment; }
#line 558 "<stdout>"
yy61:
	++YYCURSOR;
#line 259 "jx_py_scan.re"
	{
    s->line++;
    s->pos = cursor;
    s->eof = NULL;
    RET(JX_PY_NEWLINE);
  }
#line 568 "<stdout>"
yy63:
	++YYCURSOR;
#line 266 "jx_py_scan.re"
	{ 
      if(cursor == s->eof) RET(JX_PY_EOI);
      RET(JX_PY_EOI); 
    }
#line 576 "<stdout>"
yy65:
	yych = *++YYCURSOR;
	goto yy16;
yy66:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy67:
	switch(yych) {
	case 0x09:
	case 0x0B:
	case 0x0C:
	case ' ':	goto yy66;
	default:	goto yy58;
	}
yy68:
	++YYCURSOR;
#line 240 "jx_py_scan.re"
	{ RET(JX_PY_GREATER_THAN_OR_EQ); }
#line 596 "<stdout>"
yy70:
	++YYCURSOR;
#line 237 "jx_py_scan.re"
	{ RET(JX_PY_NOT_EQ); }
#line 601 "<stdout>"
yy72:
	++YYCURSOR;
#line 236 "jx_py_scan.re"
	{ RET(JX_PY_EQ_EQ); }
#line 606 "<stdout>"
yy74:
	++YYCURSOR;
#line 238 "jx_py_scan.re"
	{ RET(JX_PY_NOT_EQ); }
#line 611 "<stdout>"
yy76:
	++YYCURSOR;
#line 235 "jx_py_scan.re"
	{ RET(JX_PY_LESS_THAN_OR_EQ); }
#line 616 "<stdout>"
yy78:
	++YYCURSOR;
#line 231 "jx_py_scan.re"
	{ RET(JX_PY_SLASHSLASH); }
#line 621 "<stdout>"
yy80:
	++YYCURSOR;
#line 245 "jx_py_scan.re"
	{ RET(JX_PY_MINUS_EQUALS); }
#line 626 "<stdout>"
yy82:
	++YYCURSOR;
#line 244 "jx_py_scan.re"
	{ RET(JX_PY_PLUS_EQUALS); }
#line 631 "<stdout>"
yy84:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy85:
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy3;
	}
yy86:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy88;
	default:	goto yy87;
	}
yy87:
	YYCURSOR = YYMARKER;
	switch(yyaccept) {
	case 0: 	goto yy3;
	case 1: 	goto yy13;
	case 2: 	goto yy16;
	case 3: 	goto yy112;
	case 4: 	goto yy151;
	case 5: 	goto yy157;
	case 6: 	goto yy160;
	case 7: 	goto yy162;
	case 8: 	goto yy167;
	case 9: 	goto yy170;
	case 10: 	goto yy176;
	case 11: 	goto yy179;
	case 12: 	goto yy182;
	case 13: 	goto yy187;
	case 14: 	goto yy189;
	case 15: 	goto yy191;
	case 16: 	goto yy193;
	}
yy88:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy88;
	default:	goto yy3;
	}
yy90:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy91:
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy87;
	case '\'':	goto yy93;
	case '\\':	goto yy92;
	default:	goto yy90;
	}
yy92:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy90;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy96;
	case 'x':	goto yy95;
	default:	goto yy87;
	}
yy93:
	++YYCURSOR;
#line 212 "jx_py_scan.re"
	{ RET(JX_PY_SCON); }
#line 901 "<stdout>"
yy95:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy98;
	default:	goto yy87;
	}
yy96:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy87;
	case '\'':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy96;
	case '\\':	goto yy92;
	default:	goto yy90;
	}
yy98:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy87;
	case '\'':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy98;
	case '\\':	goto yy92;
	default:	goto yy90;
	}
yy100:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy101:
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy87;
	case '"':	goto yy103;
	case '\\':	goto yy102;
	default:	goto yy100;
	}
yy102:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy100;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy106;
	case 'x':	goto yy105;
	default:	goto yy87;
	}
yy103:
	++YYCURSOR;
#line 210 "jx_py_scan.re"
	{ RET(JX_PY_SCON); }
#line 1026 "<stdout>"
yy105:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy108;
	default:	goto yy87;
	}
yy106:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy87;
	case '"':	goto yy103;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy106;
	case '\\':	goto yy102;
	default:	goto yy100;
	}
yy108:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy87;
	case '"':	goto yy103;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy108;
	case '\\':	goto yy102;
	default:	goto yy100;
	}
yy110:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy110;
	case 'E':
	case 'e':	goto yy113;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy114;
	default:	goto yy112;
	}
yy112:
#line 208 "jx_py_scan.re"
	{ RET(JX_PY_FCON); }
#line 1135 "<stdout>"
yy113:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy115;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy116;
	default:	goto yy87;
	}
yy114:
	yych = *++YYCURSOR;
	goto yy112;
yy115:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy116;
	default:	goto yy87;
	}
yy116:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy116;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy114;
	default:	goto yy112;
	}
yy118:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'E':
	case 'e':	goto yy129;
	default:	goto yy128;
	}
yy119:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy120:
	switch(yych) {
	case '.':	goto yy118;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy119;
	case 'E':
	case 'e':	goto yy121;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy122;
	default:	goto yy13;
	}
yy121:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy124;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy125;
	default:	goto yy87;
	}
yy122:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy122;
	default:	goto yy13;
	}
yy124:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy125;
	default:	goto yy87;
	}
yy125:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy125;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy114;
	default:	goto yy112;
	}
yy127:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy128:
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy127;
	case 'E':
	case 'e':	goto yy133;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy114;
	default:	goto yy112;
	}
yy129:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy130;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy131;
	default:	goto yy87;
	}
yy130:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy131;
	default:	goto yy87;
	}
yy131:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy131;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy114;
	default:	goto yy112;
	}
yy133:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy134;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy135;
	default:	goto yy87;
	}
yy134:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy135;
	default:	goto yy87;
	}
yy135:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy135;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy114;
	default:	goto yy112;
	}
yy137:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy138:
	switch(yych) {
	case '.':	goto yy118;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy137;
	case 'E':
	case 'e':	goto yy121;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy144;
	default:	goto yy13;
	}
yy139:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy140;
	default:	goto yy87;
	}
yy140:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy140;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy142;
	default:	goto yy13;
	}
yy142:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy142;
	default:	goto yy13;
	}
yy144:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy144;
	default:	goto yy13;
	}
yy146:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 't':	goto yy147;
	default:	goto yy85;
	}
yy147:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'u':	goto yy148;
	default:	goto yy85;
	}
yy148:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'r':	goto yy149;
	default:	goto yy85;
	}
yy149:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'n':	goto yy150;
	default:	goto yy85;
	}
yy150:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy151;
	}
yy151:
#line 204 "jx_py_scan.re"
	{ RET(JX_PY_RETURN); }
#line 1630 "<stdout>"
yy152:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'm':	goto yy153;
	default:	goto yy85;
	}
yy153:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'b':	goto yy154;
	default:	goto yy85;
	}
yy154:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'd':	goto yy155;
	default:	goto yy85;
	}
yy155:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'a':	goto yy156;
	default:	goto yy85;
	}
yy156:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy157;
	}
yy157:
#line 203 "jx_py_scan.re"
	{ RET(JX_PY_LAMBDA);}
#line 1732 "<stdout>"
yy158:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'f':	goto yy161;
	case 'l':	goto yy159;
	default:	goto yy85;
	}
yy159:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy160;
	}
yy160:
#line 200 "jx_py_scan.re"
	{ RET(JX_PY_DEL); }
#line 1814 "<stdout>"
yy161:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy162;
	}
yy162:
#line 202 "jx_py_scan.re"
	{ RET(JX_PY_DEF); }
#line 1888 "<stdout>"
yy163:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'i':	goto yy164;
	default:	goto yy85;
	}
yy164:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'l':	goto yy165;
	default:	goto yy85;
	}
yy165:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'e':	goto yy166;
	default:	goto yy85;
	}
yy166:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy167;
	}
yy167:
#line 199 "jx_py_scan.re"
	{ RET(JX_PY_WHILE); }
#line 1983 "<stdout>"
yy168:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'r':	goto yy169;
	default:	goto yy85;
	}
yy169:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy170;
	}
yy170:
#line 198 "jx_py_scan.re"
	{ RET(JX_PY_FOR); }
#line 2064 "<stdout>"
yy171:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 's':	goto yy177;
	default:	goto yy85;
	}
yy172:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'i':	goto yy173;
	default:	goto yy85;
	}
yy173:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'n':	goto yy174;
	default:	goto yy85;
	}
yy174:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 't':	goto yy175;
	default:	goto yy85;
	}
yy175:
	yyaccept = 10;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy176;
	}
yy176:
#line 197 "jx_py_scan.re"
	{ RET(JX_PY_PRINT); }
#line 2166 "<stdout>"
yy177:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 's':	goto yy178;
	default:	goto yy85;
	}
yy178:
	yyaccept = 11;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy179;
	}
yy179:
#line 201 "jx_py_scan.re"
	{ RET(JX_PY_PASS); }
#line 2247 "<stdout>"
yy180:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 't':	goto yy181;
	default:	goto yy85;
	}
yy181:
	yyaccept = 12;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy182;
	}
yy182:
#line 196 "jx_py_scan.re"
	{ RET(JX_PY_NOT);}
#line 2328 "<stdout>"
yy183:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'i':	goto yy184;
	case 's':	goto yy185;
	default:	goto yy85;
	}
yy184:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'f':	goto yy188;
	default:	goto yy85;
	}
yy185:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'e':	goto yy186;
	default:	goto yy85;
	}
yy186:
	yyaccept = 13;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy187;
	}
yy187:
#line 194 "jx_py_scan.re"
	{ RET(JX_PY_ELSE); }
#line 2424 "<stdout>"
yy188:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy189;
	}
yy189:
#line 193 "jx_py_scan.re"
	{ RET(JX_PY_ELIF); }
#line 2498 "<stdout>"
yy190:
	yyaccept = 15;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy191;
	}
yy191:
#line 192 "jx_py_scan.re"
	{ RET(JX_PY_IF); }
#line 2572 "<stdout>"
yy192:
	yyaccept = 16;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy86;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy84;
	default:	goto yy193;
	}
yy193:
#line 195 "jx_py_scan.re"
	{ RET(JX_PY_IN);}
#line 2646 "<stdout>"
}
#line 278 "jx_py_scan.re"


comment:
  
#line 2653 "<stdout>"
{
	YYCTYPE yych;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:	goto yy196;
	case 0x0A:	goto yy197;
	default:	goto yy199;
	}
yy196:
yy197:
	++YYCURSOR;
#line 283 "jx_py_scan.re"
	{ 
      s->pos = cursor; s->line++;
      s->eof = NULL;
      goto std; 
    }
#line 2672 "<stdout>"
yy199:
	++YYCURSOR;
#line 290 "jx_py_scan.re"
	{ goto comment; }
#line 2677 "<stdout>"
}
#line 291 "jx_py_scan.re"

  
}


  /* not used:


#if 0
    "and"    { RET(JX_PY_AND); }
    "break"  { RET(JX_PY_BREAK); }
    "class"  { RET(JX_PY_CLASS); }

    "exec"   { RET(JX_PY_EXEC); }
    "from"   { RET(JX_PY_FROM); }
    "import" { RET(JX_PY_IMPORT); }
    "is"     { RET(JX_PY_IS);}
    "or"     { RET(JX_PY_OR);}
#endif

    ("0" [xX] H+ IS?) | ("0" D+ IS?) | ([+\-]? D+ IS?) { RET(JX_PY_ICON); }

    ([+\-]? D+ E FS?) | ([+\-]? D* "." D+ E? FS?) | ([+\-]? D+ "." D* E? FS?)  { RET(JX_PY_FCON); }

    "`" (L|D|":")+  { RET(JX_PY_BUILTIN); }
    

    "-="        { RET(JX_PY_MINUS_EQUALS); }
    "*="        { RET(JX_PY_ASTERISK_EQUALS); }
    "/="        { RET(JX_PY_SLASH_EQUALS); } 
    "%="        { RET(JX_PY_PERCENT_EQUALS); } 
    "&="        { RET(JX_PY_AND_EQUALS); } 
    "|="        { RET(JX_PY_OR_EQUALS); }
    "^="        { RET(JX_PY_CARAT_EQUALS); }
    "<<="       { RET(JX_PY_LSHFT_EQUALS); }
    ">>="       { RET(JX_PY_RSHFT_QUALS); }
    "**="       { RET(JX_PY_STARSTAR_EQUALS); } 
    "//="       { RET(JX_PY_SLASHSLASH_EQUALS); } 


    "true"      { RET(JX_PY_TRUE); }
    "false"     { RET(JX_PY_FALSE); }
    "null"      { RET(JX_PY_NULL); }
    
    "."         { RET(JX_PY_DOT); }
    "`"         { RET(JX_PY_BACKAPOSTROPHE); }



    "*"         { RET(JX_PY_ASTERISK); }
    "/"         { RET(JX_PY_SLASH); }
    "%"         { RET(JX_PY_PERCENT); }
    (['] (ESC|any\[\n\\'])* [']) { RET(JX_PY_SCON); }

   */
#define SSCANF_BUFSIZE 32

/* anticipated use cases:
   (1) parsing a string buffer from memory
   (2) parsing from a file or file descriptor (e.g. stdin) 
   (3) parsing from a character stream 
*/

JX_INLINE void jx_py_send(void *parser, int token, jx_ob ob, jx_py_parse_context *context)
{
#ifdef JX_PY_PARSER_DEBUG
  printf("scanner: sending %d\n",token);
#endif
  jx_py_(parser,token, ob, context);
}


static void jx_py_scan_input(jx_py_scanner_state *s)
{
  /* allocate parser */

  void *jx_Parser = jx_py_Alloc( (void *(*)(size_t))jx__py_alloc);
  jx_int tok_type = 0;
  jx_char stack_buffer[SSCANF_BUFSIZE];

  s->context.status = 0;
  s->n_tok_parsed = 0;
  
  while(!s->context.exhausted) {
    jx_bool skip_token = JX_FALSE;
    jx_bool indent_just_changed = JX_FALSE;
    if(!s->saved_token) 
      tok_type = jx_scan(s);
    else {
      tok_type = s->saved_token;
      s->saved_token = 0;
#ifdef JX_PY_PARSER_DEBUG
    printf("scanner: saved token index %d: \n",tok_type);
#endif
    }
#ifdef JX_PY_PARSER_DEBUG
    printf("scanner: token index %d: \n",tok_type);
    jx_jxon_dump(stdout,"scanner: indent_stack",s->indent_stack);
    printf("scanner: current_indent %d\n",s->current_indent);
    printf("scanner: newline_just_seen %d\n",s->newline_just_seen);
    printf("scanner: colon_just_seen %d\n",s->colon_just_seen);
    printf("scanner: expected indent %d\n",jx_ob_as_int(jx_list_borrow(s->indent_stack,-1)));
#endif
    /* Python / block indentation handling - UGH - COMPLEX!!! */

    if(s->newline_just_seen) { /* previous token was a newline... */
      jx_int expected_indent = jx_ob_as_int(jx_list_borrow(s->indent_stack,-1));
      switch(tok_type) {
      case JX_PY_NEWLINE:
        /* current token is also a newline --  what are the implications? */
        switch(s->mode) {
        case JX_PY_SCANNER_MODE_CONSOLE:
          { /* on the console, changes in indentation are always significant */
            if(expected_indent != s->current_indent) {
              if(s->current_indent > expected_indent) {
                jx_list_push(s->indent_stack,jx_ob_from_int(s->current_indent));
                jx_py_send(jx_Parser, JX_PY_INDENT, jx_ob_from_null(),&s->context);
                indent_just_changed = JX_TRUE;
              } else if(s->current_indent < expected_indent) {


                jx_list_pop(s->indent_stack);
                expected_indent = jx_ob_as_int(jx_list_borrow(s->indent_stack,-1));
                if(expected_indent != s->current_indent) {
                  s->context.status = JX_STATUS_SYNTAX_ERROR;
                } else {
                  jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(),&s->context); 
                  jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);        
                  indent_just_changed = JX_TRUE;
                }
              }
            }
          }
          break;
        default:
          
          /* in files, changed to invisible indentation in front of
             newlines doesn't mean anything, so just ignore indentation for now */
          s->current_indent = 0; 
          break;
        }
        break;
      case JX_PY_EOI: /* end of input reached -- back-out the indents... */
        while(jx_list_size(s->indent_stack)) {
          jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(), &s->context);        
          jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);        
          jx_list_pop(s->indent_stack);
          indent_just_changed = JX_TRUE;
        }
        break;
      default: 
        {
          /* current token not a newline, so this is for real in all cases  */

          if(expected_indent != s->current_indent) {
            if(s->current_indent > expected_indent) {
              jx_list_push(s->indent_stack,jx_ob_from_int(s->current_indent));
              jx_py_send(jx_Parser, JX_PY_INDENT, jx_ob_from_null(), &s->context);
              indent_just_changed = JX_TRUE;
            } else {
              while(s->current_indent < expected_indent) {
                jx_list_pop(s->indent_stack);
                expected_indent = jx_ob_as_int(jx_list_borrow(s->indent_stack,-1));
                jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(), &s->context); 
                switch(tok_type) {
                case JX_PY_ELIF:
                case JX_PY_ELSE:
                  break;
                default:
                  jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);
                  break;
                }
                indent_just_changed = JX_TRUE;
                if(expected_indent == s->current_indent) {
                  break;
                }
              }
              if(expected_indent != s->current_indent) {
                s->context.status = JX_STATUS_SYNTAX_ERROR;
                break;
              } else if(!s->current_indent) {
                switch(tok_type) {
                case JX_PY_ELIF:
                case JX_PY_ELSE:
                  break;
                default:
                  jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context); 
                  break;
                }
              }
            }
          }
        }
        break;
      }
    } else { /* previous token was not a newline */
      switch(tok_type) {
      case JX_PY_EOI: /* end of input reached -- back-out the indents... */
        while(jx_list_size(s->indent_stack)) {
          jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(), &s->context);        
          jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);        
          jx_list_pop(s->indent_stack);
          indent_just_changed = JX_TRUE;
        }
        break;
      }
    }

    /* address newline subtleties... */

    if(tok_type == JX_PY_NEWLINE) {
      if(s->newline_just_seen && (!indent_just_changed) && (!s->colon_just_seen)) {
        /* suppress extra newlines which don't change the indent level */
        skip_token = true;
      } else if (!s->n_tok_parsed++) {
        /* skip leading newlines in parse block */
        skip_token = true;
      } else if((!s->colon_just_seen) && 
                (!jx_list_size(s->indent_stack) || (s->newline_just_seen))) {
        /* help parser along */                             
        jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);                
      }
    }
    s->newline_just_seen = (tok_type == JX_PY_NEWLINE); /* for next time */

    if(s->newline_just_seen)
      s->current_indent = 0;

    if(s->context.status) {/* accepted or complete */
      s->saved_token = tok_type;
      break;
    }

    {
      jx_ob token = JX_OB_NULL;
      jx_size st_len = s->cur - s->tok;
      
#ifdef JX_PY_PARSER_DEBUG
      {
        jx_size i;
        jx_char *c = s->tok;
        
        printf("scanner: token: '");
        if(st_len) {
          for(i=0;i<st_len;i++) {
            printf("%c",*(c++));
          }
        }
        printf("'\n");
      }
#endif

      switch(tok_type) {
      case JX_PY_ICON:
      case JX_PY_FCON:
      case JX_PY_SCON:
      case JX_PY_NAME:
        {
          char *buffer = stack_buffer;
          if(st_len >= SSCANF_BUFSIZE) {
            buffer = jx_malloc(st_len+1);
          }
          if(buffer) {
            jx_os_strncpy(buffer, s->tok, st_len);                              
            buffer[st_len] = 0;
            switch(tok_type) {
            case JX_PY_ICON:
              {
#ifdef JX_64_BIT
                jx_int icon;
                if( jx_os_sscanf(buffer, "%lli", &icon) != 1) { /* use strtol instead? */
                  icon = 0;
                }
                token = jx_ob_from_int(icon);            
#else
                int icon;
                if( jx_os_sscanf(buffer, "%i", &icon) != 1) { /* use strtol instead? */
                  icon = 0;
                }
#endif
                token = jx_ob_from_int(icon);            
              }
              break;
            case JX_PY_FCON:
              {
#ifdef JX_64_BIT
                double fcon;
                if( jx_os_sscanf(buffer, "%lf", &fcon) != 1) { /* use strtof instead? */
                  fcon = 0.0;
                }
#else
                float fcon; 
                if( jx_os_sscanf(buffer, "%f", &fcon) != 1) { /* use strtof instead? */
                  fcon = 0.0F;
                }
#endif
                token = jx_ob_from_float(fcon);
              }
              break;
            case JX_PY_SCON:
              buffer[st_len-1]=0;
              token = jx_ob_from_str(buffer+1);
              break;
            case JX_PY_NAME:
              token = jx_ob_from_ident(buffer);
              break;
            }
            if(buffer != stack_buffer)
              jx_free(buffer);
          }
        }
        break;
#if 0
      case JX_PY_TRUE:
        token = jx_ob_from_bool(true);
        break;
      case JX_PY_FALSE:
        token = jx_ob_from_bool(false);
        break;
      case JX_PY_NULL:
        token = jx_ob_from_null();
        break;
      case JX_PY_BUILTIN:
        token = jx_builtin_new_from_selector(0);
        break;
#endif
      case JX_PY_ERROR:
        s->context.status = JX_STATUS_SYNTAX_ERROR;
        break;
      }
    
      if(tok_type == JX_PY_EOI) {
        s->context.exhausted = JX_TRUE;
      }

      if(!skip_token) {

        s->colon_just_seen = (tok_type == JX_PY_COLON);

        jx_py_send(jx_Parser, (int)tok_type, token, &s->context);

        if(!jx_ok(s->context.status)) /* something bad happened */
          break;
        
        switch(tok_type) { 
        case JX_PY_EOI:
          {/* parse a null token to enable acceptance */
            jx_ob ob = JX_OB_NULL;
            jx_py_send(jx_Parser, 0, ob, &s->context);
          }
          break;
        }
      }
      if(s->context.status) /* accepted or complete */
        break;
      else /* we need more */
        s->n_tok_parsed++;
    }
  }
  /* free the parser instance */
  jx_py_Free(jx_Parser, jx__py_free);
}

#if 0
static void jx_py_scan_input(jx_py_scanner_state *state)
{
  /* allocate parser */

  void *jx_Parser = jx_py_Alloc( (void *(*)(size_t))jx__py_alloc);
  jx_int tok_type = 0;
  jx_char stack_buffer[SSCANF_BUFSIZE];
  jx_int colon_seen = JX_FALSE;
  jx_int newline_seen = JX_FALSE;
  s->context.status = 0;
  s->n_tok_parsed = 0;

  while(!s->context.exhausted) {
    tok_type = jx_scan(state);
    {
      jx_ob token = JX_OB_NULL;
      jx_size st_len = s->cur - s->tok;
      jx_bool skip = JX_FALSE;
      
#ifdef JX_PY_PARSER_DEBUG
      
      if(1) {
        jx_size i;
        jx_char *c = s->tok;

        printf("token type %d: ",tok_type);
        
        if(st_len) {
          for(i=0;i<st_len;i++) {
            printf("%c",*(c++));
          }
          printf("\n");
        }
      }
#endif

      switch(tok_type) {
      case JX_PY_INDENT:
      case JX_PY_DEDENT:
      case JX_PY_NEWLINE:
        break;
      default:
        if(newline_seen && 
           (s->indent_level)) {
          int new_indent = (s->tok - s->pos);
          if(new_indent != s->indent_level) {
            jx_ob ob = jx_ob_from_null();
            jx_py_(jx_Parser, JX_PY_DEDENT, ob, &s->context);        
            s->indent_level = new_indent;
          }
        }
      }

      switch(tok_type) {
      case JX_PY_ICON:
      case JX_PY_FCON:
      case JX_PY_SCON:
      case JX_PY_NAME:
        {
          char *buffer = stack_buffer;
          if(st_len >= SSCANF_BUFSIZE) {
            buffer = jx_malloc(st_len+1);
          }
          if(buffer) {
            jx_os_strncpy(buffer, s->tok, st_len);                              
            buffer[st_len] = 0;
            switch(tok_type) {
            case JX_PY_ICON:
              {
#ifdef JX_64_BIT
                jx_int icon;
                if( jx_os_sscanf(buffer, "%lli", &icon) != 1) { /* use strtol instead? */
                  icon = 0;
                }
                token = jx_ob_from_int(icon);            
#else
                int icon;
                if( jx_os_sscanf(buffer, "%i", &icon) != 1) { /* use strtol instead? */
                  icon = 0;
                }
#endif
                token = jx_ob_from_int(icon);            
              }
              break;
            case JX_PY_FCON:
              {
#ifdef JX_64_BIT
                double fcon;
                if( jx_os_sscanf(buffer, "%lf", &fcon) != 1) { /* use strtof instead? */
                  fcon = 0.0;
                }
#else
                float fcon; 
                if( jx_os_sscanf(buffer, "%f", &fcon) != 1) { /* use strtof instead? */
                  fcon = 0.0F;
                }
#endif
                token = jx_ob_from_float(fcon);
              }
              break;
            case JX_PY_SCON:
              buffer[st_len-1]=0;
              token = jx_ob_from_str(buffer+1);
              break;
            case JX_PY_NAME:
              token = jx_ob_from_ident(buffer);
              break;
            }
            if(buffer != stack_buffer)
              jx_free(buffer);
          }
        }
        break;
#if 0
      case JX_PY_TRUE:
        token = jx_ob_from_bool(true);
        break;
      case JX_PY_FALSE:
        token = jx_ob_from_bool(false);
        break;
      case JX_PY_NULL:
        token = jx_ob_from_null();
        break;
      case JX_PY_BUILTIN:
        token = jx_builtin_new_from_selector(0);
        break;
#endif
      case JX_PY_DEDENT_NEWLINE:
        {
          jx_ob ob = jx_ob_from_null();
          jx_py_(jx_Parser, JX_PY_DEDENT, ob, &s->context);        
          tok_type = JX_PY_NEWLINE;
          jx_py_(jx_Parser, JX_PY_NEWLINE, ob, &s->context);        
          tok_type = JX_PY_NEWLINE;
        }
        break;
      case JX_PY_NEWLINE:
        if((!colon_seen)&&(!s->indent_level)) { /* send double newline */
          jx_ob ob = jx_ob_from_null();
          jx_py_(jx_Parser, JX_PY_NEWLINE, ob, &s->context);        
          tok_type = JX_PY_NEWLINE;
        }
        break;
      case JX_PY_ERROR:
        s->context.status = JX_STATUS_SYNTAX_ERROR;
        break;
      case JX_PY_EOI:
        skip = JX_TRUE;
        break;
      }
      
      newline_seen = (tok_type == JX_PY_NEWLINE);

      if(!skip) {
        colon_seen = (tok_type == JX_PY_COLON);
        jx_py_(jx_Parser, (int)tok_type, token, &s->context);
        
        if(!jx_ok(s->context.status)) /* something bad happened */
          break;
      }
      switch(tok_type) {
      case JX_PY_EOI:
        {/* parse a null token to enable acceptance */
          jx_ob ob = JX_OB_NULL;
          jx_py_(jx_Parser, 0, ob, &s->context);
        }
        break;
      }
      
      if(s->context.status) /* accepted or complete */
        break;
      else
        s->n_tok_parsed++;
    }
  
    if(tok_type == JX_PY_EOI) {
      s->context.exhausted = JX_TRUE;
    }
  }
  
  /* free the parser instance */
  jx_py_Free(jx_Parser, jx__py_free);
}
#endif

static jx_status jx_py_scanner_state_init(jx_py_scanner_state *state)
{
  memset(state,0,sizeof(jx_py_scanner_state));
  state->indent_stack = jx_list_new();
  return JX_SUCCESS;
}

static jx_status jx_py_scanner_state_reset(jx_py_scanner_state *state)
{
  if(state->bot) 
    jx_free(state->bot);
  state->bot = NULL;
  state->tok = NULL;
  state->ptr = NULL;
  state->cur = NULL;
  state->pos = NULL;
  state->lim = NULL;
  state->top = NULL;
  state->eof = NULL;
  state->line = 0;
  state->n_tok_parsed = 0;
  state->current_indent = 0;
  state->colon_just_seen = JX_FALSE;
  state->newline_just_seen = JX_FALSE;
  jx_list_reset(state->indent_stack);
  return JX_SUCCESS;
}

static jx_status jx_py_scanner_state_purge(jx_py_scanner_state *state)
{
  jx_ob_free(state->indent_stack);
  /* free last object */
  jx_ob_free(state->context.result);
  /* free the input buffer (if using stdin) */
  switch(state->mode) {
  case JX_PY_SCANNER_MODE_FILE:
  case JX_PY_SCANNER_MODE_CONSOLE:
    if(state->bot) 
      jx_free(state->bot);
    break;
  }
  return JX_SUCCESS;
}

void jx_py_echo_stdin(void)
{
  jx_py_scanner_state state;
  jx_py_scanner_state_init(&state);
  jx_bool done = JX_FALSE;
  while(!done) {    
    jx_py_scan_input(&state);
    switch(state.context.status) {
    case JX_STATUS_SYNTAX_ERROR:
      printf("syntax error.\n");
      break;
    case JX_YES: /* accepted */
      {
        jx_ob jxon = jx_ob_to_jxon(jx_ob_from_null(), state.context.result);
        if(state.n_tok_parsed)
          printf("%s;\n",jx_ob_as_str(&jxon));
        jx_ob_free(jxon);
      }
      state.context.result = jx_null_with_ob(state.context.result);
      break;
    case JX_FAILURE:
      done = JX_TRUE;
      break;
    }
    if(state.context.exhausted)
      done = JX_TRUE;
  }
  jx_py_scanner_state_purge(&state);
}

#define JX_PY_SCANNER_MAGIC "jxJSc"

typedef struct {
  jx_opaque_ob opaque;
  jx_py_scanner_state state;
} jx_py_scanner;

static jx_status jx_py_scanner_free(jx_py_scanner *scanner) 
{
  if(jx_ob_equal(scanner->opaque.magic,
                 jx_ob_from_str(JX_PY_SCANNER_MAGIC))) {
    jx_py_scanner_state_purge(&scanner->state);
    jx_ob_free(scanner->opaque.magic);
    jx_free(scanner);
    return JX_SUCCESS;
  }
  return JX_FAILURE;
}

jx_ob jx_py_scanner_new_with_file(FILE *file)
{
  jx_ob result = JX_OB_NULL;
  jx_py_scanner *scanner = (jx_py_scanner*)jx_calloc(1,sizeof(jx_py_scanner));
  if(scanner) {
    if(jx_ok(jx_py_scanner_state_init(&scanner->state))) {
      scanner->opaque.magic = jx_ob_from_str(JX_PY_SCANNER_MAGIC);
      scanner->opaque.free_fn = (jx_opaque_free_fn)jx_py_scanner_free;
      scanner->state.file = file;
      if (isatty((int)fileno(file))) {      
        scanner->state.mode = JX_PY_SCANNER_MODE_CONSOLE;
      } else {
        scanner->state.mode = JX_PY_SCANNER_MODE_FILE;
      }
      result = jx_builtin_new_with_opaque_ob(&scanner->opaque);
    } else 
      jx_free(scanner);
  }
  return result;
}

jx_ob jx_py_scanner_get_error_message(jx_ob scanner_ob)
{
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_py_scanner *scanner = (jx_py_scanner*)scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic,
                   jx_ob_from_str(JX_PY_SCANNER_MAGIC))) {
      jx_py_scanner_state *state = &scanner->state;
      jx_ob list = jx_list_new();
      {
        jx_char buffer[50];
        sprintf(buffer,"Error: invalid syntax on line %d\n",(int)state->line+1);
        jx_list_append(list, jx_ob_from_str(buffer));
      }
      if(state->bot != state->lim) {
        if(state->tok > state->pos) {
          jx_list_append(list, jx_ob_from_str_with_len(state->pos, state->tok - state->pos));
        } else if(state->tok > state->bot) {
          jx_list_append(list, jx_ob_from_str_with_len(state->bot, state->tok - state->bot));
        }
        if((state->cur > state->tok) && state->tok && state->tok[0]) {
          jx_list_append(list, jx_ob_from_str(" -->"));
          jx_list_append(list, jx_ob_from_str_with_len(state->tok, state->cur - state->tok));
          jx_list_append(list, jx_ob_from_str("<-- "));
          if(state->lim > state->cur) {
            jx_char *ch = state->cur;
            while( (ch<state->lim) && (*ch!='\n') &&(*ch!='\r'))
              ch++;
            jx_list_append(list, jx_ob_from_str_with_len(state->cur, ch - state->cur));
          }
        } else {
          jx_list_append(list, jx_ob_from_str("<-- (at end of input)"));
        }
      } else {
        jx_list_append(list, jx_ob_from_str("<-- (at end of input)"));
      }
      return jx_str_join_with_list(list);
    }
  }
  return jx_ob_from_null();
}

jx_status jx_py_scanner_next_ob(jx_ob *result, jx_ob scanner_ob)
{
  jx_status status = JX_FAILURE;
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_py_scanner *scanner = (jx_py_scanner*)scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic,
                   jx_ob_from_str(JX_PY_SCANNER_MAGIC))) {
      jx_py_scanner_state *state = &scanner->state;
      state->context.status = JX_SUCCESS;
      while(!state->context.status) {    
        jx_py_scan_input(state);
        switch(state->context.status) {
        case JX_YES: /* accept called */
          jx_ob_replace(result, state->context.result);
          state->context.result = jx_ob_from_null();
          status = state->n_tok_parsed ? JX_YES : JX_NO; /* but were any tokens parsed */
          break;
        default:
          status = state->context.status;
          break;
        }
        if(state->context.exhausted) {
          if(!status) 
            status = JX_STATUS_EXHAUSTED;
          break;
        }
      }
    }
  }
  return status;
}

jx_status jx_py_scanner_purge_input(jx_ob scanner_ob)
{
  jx_status status = JX_FAILURE;
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_py_scanner *scanner = (jx_py_scanner*)scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic,
                   jx_ob_from_str(JX_PY_SCANNER_MAGIC))) {
      jx_py_scanner_state *state = &scanner->state;
      jx_py_scanner_state_reset(state);
      status = JX_SUCCESS;
    }
  }
  return status;
}
