/* Generated by re2c 0.12.3 on Wed Jul  8 16:01:48 2009 */
#line 1 "jx_py_scan.re"
/* RE2C-based tokenizer */

/* 
Copyright (c) 2009, DeLano Scientific LLC, Palo Alto, California, USA.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in the
 documentation and/or other materials provided with the distribution.

* Neither the name of the DeLano Scientific LLC nor the names of its
 contributors may be used to endorse or promote products derived from
 this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "jx_py_private.h"

#define JX_PY_SCANNER_MODE_FILE    0 
#define JX_PY_SCANNER_MODE_STRING  1
#define JX_PY_SCANNER_MODE_CONSOLE 2

typedef struct {
  jx_char *bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
  jx_int line;
  jx_int n_tok_parsed;
  jx_int mode,flags;
  FILE *file;
  jx_py_parse_context context;
  jx_ob indent_stack;
  jx_bool ignore_whitesp;
  jx_int current_indent;
  jx_bool newline_just_seen;
  jx_bool colon_just_seen;
  jx_bool saved_token;
  jx_ob saved_token_ob;
} jx_py_scanner_state;

#ifndef true
#define true 1
#endif

#ifndef false
#define false 0
#endif

#define   BSIZE   8192

#define   YYCTYPE     jx_char
#define   YYCURSOR    cursor
#define   YYLIMIT     s->lim
#define   YYMARKER    s->ptr
#define   YYFILL(n)   {cursor = jx_fill(s, cursor);}

#define   RET(i)   {s->cur = cursor; return i;}

#ifndef JX_PY_EOI
#define JX_PY_EOI -1
#endif

#ifndef JX_PY_DEDENT_NEWLINE
#define JX_PY_DEDENT_NEWLINE -2
#endif

/* parser allocator */

static void *jx__py_alloc(jx_size bytes)
{
  jx_char *ptr = NULL;
  ptr = jx_calloc(1,bytes);
  return (void*)ptr;
}

static void jx__py_free(void *ptr)
{
  if(ptr) 
    jx_free(ptr);
}

static jx_size jx_read_file(FILE *file, jx_char *buf, jx_size buf_size, jx_int mode)
{
  switch(mode) {
  case JX_PY_SCANNER_MODE_FILE:
    return fread((char*)buf, 1, buf_size, file);
    break;
  case JX_PY_SCANNER_MODE_CONSOLE:
    if(fgets((char*)buf, buf_size, file)) {
      return jx_strlen(buf);
    } else 
      return 0;
    break;
  }
  return 0;
}

static jx_char *jx_fill(jx_py_scanner_state *s, jx_char *cursor)
{
  switch(s->mode) {
  case JX_PY_SCANNER_MODE_FILE:
  case JX_PY_SCANNER_MODE_CONSOLE:
    if(!s->eof) { /* only fill if eof is not set (known) */
      jx_diff cnt = s->tok - s->bot; /* amount of open space in buffer */
      if(cnt) {
        if(s->lim > s->tok) { /* any remaining characters? */
          jx_os_memcpy(s->bot, s->tok, s->lim - s->tok); /* move to start of buffer */
        }
        s->tok = s->bot;  /* shift pointers accordingly */
        s->ptr -= cnt; 
        cursor -= cnt;
        s->pos -= cnt;
        s->lim -= cnt;
      }
      if((s->top - s->lim) < BSIZE) { /* open space less than read quantum? */
        /* allocate a larger buffer */
        jx_char *buf = (jx_char*) jx_calloc(1,((s->lim - s->bot) +
                                               BSIZE)*sizeof(jx_char));
        if(buf) { /* and copy contents to new buffer */
          jx_os_memcpy(buf, s->tok, s->lim - s->tok);
          s->tok = buf; /* adjust pointers accordingly */
          s->ptr = &buf[s->ptr - s->bot];
          cursor = &buf[cursor - s->bot];
          s->pos = &buf[s->pos - s->bot];
          s->lim = &buf[s->lim - s->bot];
          s->top = &s->lim[BSIZE];
          if(s->bot) { /* free old buffer (if exists) */
            jx_free(s->bot);
          }
          s->bot = buf; /* use the new buffer from now on */
        }
      }
      if((s->top - s->lim) < BSIZE) {
        /* unhandled error condition */
      } else {
        cnt = jx_read_file(s->file, s->lim, BSIZE, s->mode);
        if(cnt != BSIZE) {
          jx_size cc = cnt;
          while(cc<BSIZE) {
            s->lim[cc] = 0;
            cc++;
          }
          s->eof = &s->lim[cnt]; 
          if(cnt) { /* short read ...there may be more to come */
            s->eof++; 
          } else { /* nothing read, so set the null sentinel */
            *(s->eof) = 0;
          }
        }
        s->lim += cnt;
      }
    }
    break;
  }
  return cursor;
}
  
static int jx_scan(jx_py_scanner_state *s)
{
  jx_char *cursor = s->cur;
 std:
  s->tok = cursor;
  
  
#line 184 "<stdout>"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:	goto yy68;
	case 0x09:
	case 0x0B:
	case 0x0C:
	case ' ':	goto yy62;
	case 0x0A:	goto yy66;
	case '!':	goto yy53;
	case '"':	goto yy21;
	case '#':	goto yy64;
	case '%':	goto yy47;
	case '\'':	goto yy23;
	case '(':	goto yy29;
	case ')':	goto yy31;
	case '*':	goto yy43;
	case '+':	goto yy39;
	case ',':	goto yy60;
	case '-':	goto yy41;
	case '.':	goto yy19;
	case '/':	goto yy45;
	case '0':	goto yy16;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy18;
	case ':':	goto yy56;
	case ';':	goto yy58;
	case '<':	goto yy49;
	case '=':	goto yy51;
	case '>':	goto yy54;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'o':
	case 'q':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy24;
	case 'F':	goto yy15;
	case 'N':	goto yy13;
	case 'T':	goto yy14;
	case '[':	goto yy25;
	case ']':	goto yy27;
	case 'c':	goto yy12;
	case 'd':	goto yy9;
	case 'e':	goto yy4;
	case 'f':	goto yy7;
	case 'i':	goto yy2;
	case 'l':	goto yy10;
	case 'n':	goto yy5;
	case 'p':	goto yy6;
	case 'r':	goto yy11;
	case 'w':	goto yy8;
	case '{':	goto yy33;
	case '}':	goto yy35;
	case '~':	goto yy37;
	default:	goto yy70;
	}
yy2:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case 'f':	goto yy216;
	case 'n':	goto yy218;
	default:	goto yy92;
	}
yy3:
#line 221 "jx_py_scan.re"
	{ RET(JX_PY_NAME); }
#line 296 "<stdout>"
yy4:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'l':	goto yy209;
	default:	goto yy92;
	}
yy5:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'o':	goto yy206;
	default:	goto yy92;
	}
yy6:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'a':	goto yy197;
	case 'r':	goto yy198;
	default:	goto yy92;
	}
yy7:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'o':	goto yy194;
	default:	goto yy92;
	}
yy8:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'h':	goto yy189;
	default:	goto yy92;
	}
yy9:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'e':	goto yy184;
	default:	goto yy92;
	}
yy10:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'a':	goto yy178;
	default:	goto yy92;
	}
yy11:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'e':	goto yy172;
	default:	goto yy92;
	}
yy12:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'l':	goto yy167;
	default:	goto yy92;
	}
yy13:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'o':	goto yy163;
	default:	goto yy92;
	}
yy14:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'r':	goto yy159;
	default:	goto yy92;
	}
yy15:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'a':	goto yy154;
	default:	goto yy92;
	}
yy16:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy130;
	case 'X':
	case 'x':	goto yy147;
	default:	goto yy146;
	}
yy17:
#line 213 "jx_py_scan.re"
	{ RET(JX_PY_ICON); }
#line 385 "<stdout>"
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy128;
yy19:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy118;
	default:	goto yy20;
	}
yy20:
#line 261 "jx_py_scan.re"
	{ RET(JX_PY_DOT); }
#line 408 "<stdout>"
yy21:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy22;
	default:	goto yy109;
	}
yy22:
#line 285 "jx_py_scan.re"
	{
#ifdef JX_PY_PARSER_DEBUG
      printf("unexpected character: %c\n", *s->tok);
#endif
       RET(JX_PY_ERROR);
    }
#line 425 "<stdout>"
yy23:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy22;
	default:	goto yy99;
	}
yy24:
	yych = *++YYCURSOR;
	goto yy92;
yy25:
	++YYCURSOR;
#line 223 "jx_py_scan.re"
	{ s->ignore_whitesp++; RET(JX_PY_OPEN_RECT_BRACE); }
#line 441 "<stdout>"
yy27:
	++YYCURSOR;
#line 224 "jx_py_scan.re"
	{ s->ignore_whitesp--; RET(JX_PY_CLOSE_RECT_BRACE); }
#line 446 "<stdout>"
yy29:
	++YYCURSOR;
#line 226 "jx_py_scan.re"
	{ s->ignore_whitesp++; RET(JX_PY_OPEN_PAR); }
#line 451 "<stdout>"
yy31:
	++YYCURSOR;
#line 227 "jx_py_scan.re"
	{ s->ignore_whitesp--; RET(JX_PY_CLOSE_PAR); }
#line 456 "<stdout>"
yy33:
	++YYCURSOR;
#line 229 "jx_py_scan.re"
	{  s->ignore_whitesp++; RET(JX_PY_OPEN_CURLY_BRACE); }
#line 461 "<stdout>"
yy35:
	++YYCURSOR;
#line 230 "jx_py_scan.re"
	{  s->ignore_whitesp--; RET(JX_PY_CLOSE_CURLY_BRACE); }
#line 466 "<stdout>"
yy37:
	++YYCURSOR;
#line 232 "jx_py_scan.re"
	{ RET(JX_PY_TILDE); }
#line 471 "<stdout>"
yy39:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy89;
	default:	goto yy40;
	}
yy40:
#line 233 "jx_py_scan.re"
	{ RET(JX_PY_PLUS); }
#line 481 "<stdout>"
yy41:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy87;
	default:	goto yy42;
	}
yy42:
#line 234 "jx_py_scan.re"
	{ RET(JX_PY_MINUS); }
#line 491 "<stdout>"
yy43:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '*':	goto yy85;
	default:	goto yy44;
	}
yy44:
#line 237 "jx_py_scan.re"
	{ RET(JX_PY_ASTERISK); }
#line 501 "<stdout>"
yy45:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '/':	goto yy83;
	default:	goto yy46;
	}
yy46:
#line 238 "jx_py_scan.re"
	{ RET(JX_PY_SLASH); }
#line 511 "<stdout>"
yy47:
	++YYCURSOR;
#line 240 "jx_py_scan.re"
	{ RET(JX_PY_PERCENT); }
#line 516 "<stdout>"
yy49:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy81;
	case '>':	goto yy79;
	default:	goto yy50;
	}
yy50:
#line 242 "jx_py_scan.re"
	{ RET(JX_PY_LESS_THAN); }
#line 527 "<stdout>"
yy51:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy77;
	default:	goto yy52;
	}
yy52:
#line 250 "jx_py_scan.re"
	{ RET(JX_PY_EQUALS); }
#line 537 "<stdout>"
yy53:
	yych = *++YYCURSOR;
	switch(yych) {
	case '=':	goto yy75;
	default:	goto yy22;
	}
yy54:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy73;
	default:	goto yy55;
	}
yy55:
#line 247 "jx_py_scan.re"
	{ RET(JX_PY_GREATER_THAN); }
#line 553 "<stdout>"
yy56:
	++YYCURSOR;
#line 255 "jx_py_scan.re"
	{ RET(JX_PY_COLON); }
#line 558 "<stdout>"
yy58:
	++YYCURSOR;
#line 257 "jx_py_scan.re"
	{ RET(JX_PY_SEMICOLON); }
#line 563 "<stdout>"
yy60:
	++YYCURSOR;
#line 259 "jx_py_scan.re"
	{ RET(JX_PY_COMMA); }
#line 568 "<stdout>"
yy62:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy72;
yy63:
#line 263 "jx_py_scan.re"
	{ if(s->pos == s->tok) 
                    s->current_indent = cursor - s->pos;
                  goto std; }
#line 578 "<stdout>"
yy64:
	++YYCURSOR;
#line 267 "jx_py_scan.re"
	{ goto comment; }
#line 583 "<stdout>"
yy66:
	++YYCURSOR;
#line 269 "jx_py_scan.re"
	{
    s->line++;
    s->pos = cursor;
    s->eof = NULL;
    if(!s->ignore_whitesp) {
       RET(JX_PY_NEWLINE);
    } else {
       goto std;
    }
  }
#line 597 "<stdout>"
yy68:
	++YYCURSOR;
#line 280 "jx_py_scan.re"
	{ 
      if(cursor == s->eof) RET(JX_PY_EOI);
      RET(JX_PY_EOI); 
    }
#line 605 "<stdout>"
yy70:
	yych = *++YYCURSOR;
	goto yy22;
yy71:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy72:
	switch(yych) {
	case 0x09:
	case 0x0B:
	case 0x0C:
	case ' ':	goto yy71;
	default:	goto yy63;
	}
yy73:
	++YYCURSOR;
#line 248 "jx_py_scan.re"
	{ RET(JX_PY_GREATER_THAN_OR_EQ); }
#line 625 "<stdout>"
yy75:
	++YYCURSOR;
#line 245 "jx_py_scan.re"
	{ RET(JX_PY_NOT_EQ); }
#line 630 "<stdout>"
yy77:
	++YYCURSOR;
#line 244 "jx_py_scan.re"
	{ RET(JX_PY_EQ_EQ); }
#line 635 "<stdout>"
yy79:
	++YYCURSOR;
#line 246 "jx_py_scan.re"
	{ RET(JX_PY_NOT_EQ); }
#line 640 "<stdout>"
yy81:
	++YYCURSOR;
#line 243 "jx_py_scan.re"
	{ RET(JX_PY_LESS_THAN_OR_EQ); }
#line 645 "<stdout>"
yy83:
	++YYCURSOR;
#line 239 "jx_py_scan.re"
	{ RET(JX_PY_SLASHSLASH); }
#line 650 "<stdout>"
yy85:
	++YYCURSOR;
#line 236 "jx_py_scan.re"
	{ RET(JX_PY_DOUBLE_ASTERISK); }
#line 655 "<stdout>"
yy87:
	++YYCURSOR;
#line 253 "jx_py_scan.re"
	{ RET(JX_PY_MINUS_EQUALS); }
#line 660 "<stdout>"
yy89:
	++YYCURSOR;
#line 252 "jx_py_scan.re"
	{ RET(JX_PY_PLUS_EQUALS); }
#line 665 "<stdout>"
yy91:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy92:
	switch(yych) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy3;
	}
yy93:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '.':	goto yy94;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy96;
	default:	goto yy3;
	}
yy94:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy96;
	default:	goto yy95;
	}
yy95:
	YYCURSOR = YYMARKER;
	switch(yyaccept) {
	case 0: 	goto yy17;
	case 1: 	goto yy22;
	case 2: 	goto yy3;
	case 3: 	goto yy120;
	}
yy96:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy96;
	default:	goto yy3;
	}
yy98:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy99:
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy95;
	case '\'':	goto yy101;
	case '\\':	goto yy100;
	default:	goto yy98;
	}
yy100:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy98;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy104;
	case 'x':	goto yy103;
	default:	goto yy95;
	}
yy101:
	++YYCURSOR;
#line 219 "jx_py_scan.re"
	{ RET(JX_PY_SCON); }
#line 982 "<stdout>"
yy103:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy106;
	default:	goto yy95;
	}
yy104:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy95;
	case '\'':	goto yy101;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy104;
	case '\\':	goto yy100;
	default:	goto yy98;
	}
yy106:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy95;
	case '\'':	goto yy101;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy106;
	case '\\':	goto yy100;
	default:	goto yy98;
	}
yy108:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy109:
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy95;
	case '"':	goto yy111;
	case '\\':	goto yy110;
	default:	goto yy108;
	}
yy110:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy108;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy114;
	case 'x':	goto yy113;
	default:	goto yy95;
	}
yy111:
	++YYCURSOR;
#line 217 "jx_py_scan.re"
	{ RET(JX_PY_SCON); }
#line 1107 "<stdout>"
yy113:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy116;
	default:	goto yy95;
	}
yy114:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy95;
	case '"':	goto yy111;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy114;
	case '\\':	goto yy110;
	default:	goto yy108;
	}
yy116:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy95;
	case '"':	goto yy111;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy116;
	case '\\':	goto yy110;
	default:	goto yy108;
	}
yy118:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy118;
	case 'E':
	case 'e':	goto yy121;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy122;
	default:	goto yy120;
	}
yy120:
#line 215 "jx_py_scan.re"
	{ RET(JX_PY_FCON); }
#line 1216 "<stdout>"
yy121:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy123;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy124;
	default:	goto yy95;
	}
yy122:
	yych = *++YYCURSOR;
	goto yy120;
yy123:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy124;
	default:	goto yy95;
	}
yy124:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy124;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy122;
	default:	goto yy120;
	}
yy126:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'E':
	case 'e':	goto yy137;
	default:	goto yy136;
	}
yy127:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy128:
	switch(yych) {
	case '.':	goto yy126;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy127;
	case 'E':
	case 'e':	goto yy129;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy130;
	default:	goto yy17;
	}
yy129:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy132;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy133;
	default:	goto yy95;
	}
yy130:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy130;
	default:	goto yy17;
	}
yy132:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy133;
	default:	goto yy95;
	}
yy133:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy133;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy122;
	default:	goto yy120;
	}
yy135:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy136:
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy135;
	case 'E':
	case 'e':	goto yy141;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy122;
	default:	goto yy120;
	}
yy137:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy138;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy139;
	default:	goto yy95;
	}
yy138:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy139;
	default:	goto yy95;
	}
yy139:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy139;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy122;
	default:	goto yy120;
	}
yy141:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy142;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy143;
	default:	goto yy95;
	}
yy142:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy143;
	default:	goto yy95;
	}
yy143:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy143;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy122;
	default:	goto yy120;
	}
yy145:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy146:
	switch(yych) {
	case '.':	goto yy126;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy145;
	case 'E':
	case 'e':	goto yy129;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy152;
	default:	goto yy17;
	}
yy147:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy148;
	default:	goto yy95;
	}
yy148:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy148;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy150;
	default:	goto yy17;
	}
yy150:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy150;
	default:	goto yy17;
	}
yy152:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy152;
	default:	goto yy17;
	}
yy154:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'l':	goto yy155;
	default:	goto yy92;
	}
yy155:
	yych = *++YYCURSOR;
	switch(yych) {
	case 's':	goto yy156;
	default:	goto yy92;
	}
yy156:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'e':	goto yy157;
	default:	goto yy92;
	}
yy157:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy158;
	}
yy158:
#line 211 "jx_py_scan.re"
	{ RET(JX_PY_FALSE); }
#line 1700 "<stdout>"
yy159:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'u':	goto yy160;
	default:	goto yy92;
	}
yy160:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'e':	goto yy161;
	default:	goto yy92;
	}
yy161:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy162;
	}
yy162:
#line 210 "jx_py_scan.re"
	{ RET(JX_PY_TRUE); }
#line 1785 "<stdout>"
yy163:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'n':	goto yy164;
	default:	goto yy92;
	}
yy164:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'e':	goto yy165;
	default:	goto yy92;
	}
yy165:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy166;
	}
yy166:
#line 209 "jx_py_scan.re"
	{ RET(JX_PY_NONE); }
#line 1870 "<stdout>"
yy167:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'a':	goto yy168;
	default:	goto yy92;
	}
yy168:
	yych = *++YYCURSOR;
	switch(yych) {
	case 's':	goto yy169;
	default:	goto yy92;
	}
yy169:
	yych = *++YYCURSOR;
	switch(yych) {
	case 's':	goto yy170;
	default:	goto yy92;
	}
yy170:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy171;
	}
yy171:
#line 207 "jx_py_scan.re"
	{ RET(JX_PY_CLASS); }
#line 1961 "<stdout>"
yy172:
	yych = *++YYCURSOR;
	switch(yych) {
	case 't':	goto yy173;
	default:	goto yy92;
	}
yy173:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'u':	goto yy174;
	default:	goto yy92;
	}
yy174:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'r':	goto yy175;
	default:	goto yy92;
	}
yy175:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'n':	goto yy176;
	default:	goto yy92;
	}
yy176:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy177;
	}
yy177:
#line 206 "jx_py_scan.re"
	{ RET(JX_PY_RETURN); }
#line 2058 "<stdout>"
yy178:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'm':	goto yy179;
	default:	goto yy92;
	}
yy179:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'b':	goto yy180;
	default:	goto yy92;
	}
yy180:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'd':	goto yy181;
	default:	goto yy92;
	}
yy181:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'a':	goto yy182;
	default:	goto yy92;
	}
yy182:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy183;
	}
yy183:
#line 205 "jx_py_scan.re"
	{ RET(JX_PY_LAMBDA);}
#line 2155 "<stdout>"
yy184:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'f':	goto yy187;
	case 'l':	goto yy185;
	default:	goto yy92;
	}
yy185:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy186;
	}
yy186:
#line 202 "jx_py_scan.re"
	{ RET(JX_PY_DEL); }
#line 2235 "<stdout>"
yy187:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy188;
	}
yy188:
#line 204 "jx_py_scan.re"
	{ RET(JX_PY_DEF); }
#line 2308 "<stdout>"
yy189:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'i':	goto yy190;
	default:	goto yy92;
	}
yy190:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'l':	goto yy191;
	default:	goto yy92;
	}
yy191:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'e':	goto yy192;
	default:	goto yy92;
	}
yy192:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy193;
	}
yy193:
#line 201 "jx_py_scan.re"
	{ RET(JX_PY_WHILE); }
#line 2399 "<stdout>"
yy194:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'r':	goto yy195;
	default:	goto yy92;
	}
yy195:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy196;
	}
yy196:
#line 200 "jx_py_scan.re"
	{ RET(JX_PY_FOR); }
#line 2478 "<stdout>"
yy197:
	yych = *++YYCURSOR;
	switch(yych) {
	case 's':	goto yy203;
	default:	goto yy92;
	}
yy198:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'i':	goto yy199;
	default:	goto yy92;
	}
yy199:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'n':	goto yy200;
	default:	goto yy92;
	}
yy200:
	yych = *++YYCURSOR;
	switch(yych) {
	case 't':	goto yy201;
	default:	goto yy92;
	}
yy201:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy202;
	}
yy202:
#line 199 "jx_py_scan.re"
	{ RET(JX_PY_PRINT); }
#line 2575 "<stdout>"
yy203:
	yych = *++YYCURSOR;
	switch(yych) {
	case 's':	goto yy204;
	default:	goto yy92;
	}
yy204:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy205;
	}
yy205:
#line 203 "jx_py_scan.re"
	{ RET(JX_PY_PASS); }
#line 2654 "<stdout>"
yy206:
	yych = *++YYCURSOR;
	switch(yych) {
	case 't':	goto yy207;
	default:	goto yy92;
	}
yy207:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy208;
	}
yy208:
#line 198 "jx_py_scan.re"
	{ RET(JX_PY_NOT);}
#line 2733 "<stdout>"
yy209:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'i':	goto yy210;
	case 's':	goto yy211;
	default:	goto yy92;
	}
yy210:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'f':	goto yy214;
	default:	goto yy92;
	}
yy211:
	yych = *++YYCURSOR;
	switch(yych) {
	case 'e':	goto yy212;
	default:	goto yy92;
	}
yy212:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy213;
	}
yy213:
#line 196 "jx_py_scan.re"
	{ RET(JX_PY_ELSE); }
#line 2825 "<stdout>"
yy214:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy215;
	}
yy215:
#line 195 "jx_py_scan.re"
	{ RET(JX_PY_ELIF); }
#line 2898 "<stdout>"
yy216:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy217;
	}
yy217:
#line 194 "jx_py_scan.re"
	{ RET(JX_PY_IF); }
#line 2971 "<stdout>"
yy218:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '.':	goto yy93;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy91;
	default:	goto yy219;
	}
yy219:
#line 197 "jx_py_scan.re"
	{ RET(JX_PY_IN);}
#line 3044 "<stdout>"
}
#line 292 "jx_py_scan.re"


comment:
  
#line 3051 "<stdout>"
{
	YYCTYPE yych;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:	goto yy222;
	case 0x0A:	goto yy223;
	default:	goto yy225;
	}
yy222:
yy223:
	++YYCURSOR;
#line 297 "jx_py_scan.re"
	{ 
      if((s->flags & JX_SCANNER_FLAG_ECHO_COMMENTS) &&
         (cursor > s->tok)) {
         fwrite(s->tok,(cursor-s->tok),1,stdout);
       }
      s->pos = cursor; s->line++;
      s->eof = NULL;
      goto std; 
    }
#line 3074 "<stdout>"
yy225:
	++YYCURSOR;
#line 308 "jx_py_scan.re"
	{ goto comment; }
#line 3079 "<stdout>"
}
#line 309 "jx_py_scan.re"

  
}


  /* not used:


#if 0
    "and"    { RET(JX_PY_AND); }
    "break"  { RET(JX_PY_BREAK); }

    "exec"   { RET(JX_PY_EXEC); }
    "from"   { RET(JX_PY_FROM); }
    "import" { RET(JX_PY_IMPORT); }
    "is"     { RET(JX_PY_IS);}
    "or"     { RET(JX_PY_OR);}
#endif

    ("0" [xX] H+ IS?) | ("0" D+ IS?) | ([+\-]? D+ IS?) { RET(JX_PY_ICON); }

    ([+\-]? D+ E FS?) | ([+\-]? D* "." D+ E? FS?) | ([+\-]? D+ "." D* E? FS?)  { RET(JX_PY_FCON); }

    "`" (L|D|":")+  { RET(JX_PY_BUILTIN); }
    

    "-="        { RET(JX_PY_MINUS_EQUALS); }
    "*="        { RET(JX_PY_ASTERISK_EQUALS); }
    "/="        { RET(JX_PY_SLASH_EQUALS); } 
    "%="        { RET(JX_PY_PERCENT_EQUALS); } 
    "&="        { RET(JX_PY_AND_EQUALS); } 
    "|="        { RET(JX_PY_OR_EQUALS); }
    "^="        { RET(JX_PY_CARAT_EQUALS); }
    "<<="       { RET(JX_PY_LSHFT_EQUALS); }
    ">>="       { RET(JX_PY_RSHFT_QUALS); }
    "**="       { RET(JX_PY_STARSTAR_EQUALS); } 
    "//="       { RET(JX_PY_SLASHSLASH_EQUALS); } 


    "true"      { RET(JX_PY_TRUE); }
    "false"     { RET(JX_PY_FALSE); }
    "null"      { RET(JX_PY_NULL); }
    
    "`"         { RET(JX_PY_BACKAPOSTROPHE); }



    "*"         { RET(JX_PY_ASTERISK); }
    "/"         { RET(JX_PY_SLASH); }
    "%"         { RET(JX_PY_PERCENT); }
    (['] (ESC|any\[\n\\'])* [']) { RET(JX_PY_SCON); }

   */
#define SSCANF_BUFSIZE 32

/* anticipated use cases:
   (1) parsing a string buffer from memory
   (2) parsing from a file or file descriptor (e.g. stdin) 
   (3) parsing from a character stream 
*/

JX_INLINE int jx_py_send(void *parser, int token, jx_ob ob, jx_py_parse_context *context)
{
#ifdef JX_PY_PARSER_DEBUG
  printf("scanner: sending %d\n",token);
#endif
  jx_py_(parser,token, ob, context);
  return context->status;
}

JX_INLINE void jx_py_save_token(jx_py_scanner_state *s, int tok_type)
{
  if(tok_type) {
#ifdef JX_PY_PARSER_DEBUG
    printf(" saving tok_type %d: \n",tok_type);
#endif
  }
  s->saved_token = tok_type;
}

static void jx_py_scan_input(jx_py_scanner_state *s)
{
  /* allocate parser */

  void *jx_Parser = jx_py_Alloc( (void *(*)(size_t))jx__py_alloc);
  jx_int tok_type = 0;
  jx_char stack_buffer[SSCANF_BUFSIZE];

  s->context.status = 0;
  s->n_tok_parsed = 0;
  
  while((!s->context.exhausted)&&(!s->context.status)) {
    jx_bool skip_token = JX_FALSE;
    jx_bool indent_just_changed = JX_FALSE;
    if(s->saved_token)  {
      tok_type = s->saved_token;
      s->saved_token = 0;
#ifdef JX_PY_PARSER_DEBUG
      printf("scanner: restored saved token index %d: \n",tok_type);
#endif
    } else {
#ifdef JX_PY_PARSER_DEBUG
      printf("scanner: scanning for next token...\n");
#endif
      tok_type = jx_scan(s);
    }

#ifdef JX_PY_PARSER_DEBUG
      printf(" tok_type: %d ",tok_type);
      printf(" current_indent: %d ",s->current_indent);
      printf(" newline_just_seen: %d ",s->newline_just_seen);
      printf(" colon_just_seen: %d ",s->colon_just_seen);
      printf(" expected_indent: %d ",jx_ob_as_int(jx_list_borrow(s->indent_stack,-1)));
      jx_jxon_dump(stdout," indent_stack",s->indent_stack);
#endif
    /* Python / block indentation handling - UGH - COMPLEX!!! */

    if(s->newline_just_seen) { /* previous token was a newline... */
      jx_int expected_indent = jx_ob_as_int(jx_list_borrow(s->indent_stack,-1));
      switch(tok_type) {
      case JX_PY_NEWLINE:
        /* current token is also a newline --  what are the implications? */
        switch(s->mode) {
        case JX_PY_SCANNER_MODE_CONSOLE:
          { /* on the console, changes in indentation are always significant */
            if(!s->ignore_whitesp) {
              if(expected_indent != s->current_indent) {
                if(s->current_indent > expected_indent) {
                  jx_list_push(s->indent_stack,jx_ob_from_int(s->current_indent));
                  if(jx_py_send(jx_Parser, JX_PY_INDENT, jx_ob_from_null(),&s->context))
                    jx_py_save_token(s,tok_type);
                  indent_just_changed = JX_TRUE;
                } else if(expected_indent > s->current_indent) {
                  while((expected_indent > s->current_indent) && (!s->context.status)) {
                    jx_list_pop(s->indent_stack);
                    expected_indent = jx_ob_as_int(jx_list_borrow(s->indent_stack,-1));
                    if(expected_indent < s->current_indent) {
                      s->context.status = JX_STATUS_SYNTAX_ERROR;
                      break;
                    } else {
                      if(jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(),&s->context))
                        jx_py_save_token(s,tok_type);
                      if(jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context))
                        jx_py_save_token(s,tok_type);
                      indent_just_changed = JX_TRUE;
                    }
                  }
                }
              }
            }
          }
          break;
        default:
          
          /* in files, changed to invisible indentation in front of
             newlines doesn't mean anything, so just ignore indentation for now */
          s->current_indent = 0; 
          break;
        }
        break;
      case JX_PY_EOI: /* end of input reached -- back-out the indents... */
        while(jx_list_size(s->indent_stack)) {
          jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(), &s->context);        
          jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);        
          jx_list_pop(s->indent_stack);
          indent_just_changed = JX_TRUE;
        }
        break;
      default: 
        {
          /* current token not a newline, so this is for real in all cases  */
          if(!s->ignore_whitesp) {
            if(expected_indent != s->current_indent) {
              if(s->current_indent > expected_indent) {
                jx_list_push(s->indent_stack,jx_ob_from_int(s->current_indent));
                if(jx_py_send(jx_Parser, JX_PY_INDENT, jx_ob_from_null(), &s->context)) 
                  jx_py_save_token(s,tok_type);
                indent_just_changed = JX_TRUE;
              } else {
                while(s->current_indent < expected_indent) {
                  jx_list_pop(s->indent_stack);
                  expected_indent = jx_ob_as_int(jx_list_borrow(s->indent_stack,-1));
                  if(jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(), &s->context))
                    jx_py_save_token(s,tok_type);
                  switch(tok_type) {
                  case JX_PY_ELIF:
                  case JX_PY_ELSE:
                    break;
                  default:
                    if(jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context))
                      jx_py_save_token(s,tok_type);
                    break;
                  }
                  indent_just_changed = JX_TRUE;
                  if(expected_indent == s->current_indent) {
                    break;
                  }
                }
                if(expected_indent != s->current_indent) {
                  s->context.status = JX_STATUS_SYNTAX_ERROR;
                  break;
                } else if(!s->current_indent) {
                  switch(tok_type) {
                  case JX_PY_ELIF:
                  case JX_PY_ELSE:
                    break;
                  default:
                    if(jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context)) 
                      jx_py_save_token(s,tok_type);
                    break;
                  }
                }
              }
            }
          }
        }
        break;
      }
    } else { /* previous token was not a newline */
      switch(tok_type) {
      case JX_PY_EOI: /* end of input reached -- back-out the indents... */
        while(jx_list_size(s->indent_stack)) {
          jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(), &s->context);        
          jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);        
          jx_list_pop(s->indent_stack);
          indent_just_changed = JX_TRUE;
        }
        break;
      }
    }

    /* address newline subtleties... */

    if(tok_type == JX_PY_NEWLINE) {
      if(s->newline_just_seen && (!indent_just_changed) && (!s->colon_just_seen)) {
        /* suppress extra newlines which don't change the indent level */
        skip_token = true;
      } else if (!s->n_tok_parsed++) {
        /* skip leading newlines in parse block */
        skip_token = true;
      } else if((!s->colon_just_seen) && 
                (!jx_list_size(s->indent_stack) || (s->newline_just_seen))) {
        /* help parser along */                             
        if(jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context))
          jx_py_save_token(s,tok_type);
      }
    }
    s->newline_just_seen = (tok_type == JX_PY_NEWLINE); /* for next time */

    if(s->newline_just_seen)
      s->current_indent = 0;

    if(s->context.status) {/* accepted or complete */
      break;
    }

    {
      jx_ob token = JX_OB_NULL;
      jx_size st_len = s->cur - s->tok;
      
#ifdef JX_PY_PARSER_DEBUG
      {
        jx_size i;
        jx_char *c = s->tok;
        
        printf("scanner: TOKEN:          '");
        if(st_len) {
          for(i=0;i<st_len;i++) {
            jx_char ch = *(c++);
            if(ch>=31) 
              printf("%c",ch);
            else
              printf("\\x%02x",ch);
          }
        }
        printf("'\n");
      }
#endif

      switch(tok_type) {
      case JX_PY_ICON:
      case JX_PY_FCON:
      case JX_PY_SCON:
      case JX_PY_NAME:
        {
          char *buffer = stack_buffer;
          if(st_len >= SSCANF_BUFSIZE) {
            buffer = jx_malloc(st_len+1);
          }
          if(buffer) {
            jx_os_strncpy(buffer, s->tok, st_len);                              
            buffer[st_len] = 0;
            switch(tok_type) {
            case JX_PY_ICON:
              {
#ifdef JX_64_BIT
                jx_int icon;
                if( jx_os_sscanf(buffer, "%lli", &icon) != 1) { /* use strtol instead? */
                  icon = 0;
                }
                token = jx_ob_from_int(icon);            
#else
                int icon;
                if( jx_os_sscanf(buffer, "%i", &icon) != 1) { /* use strtol instead? */
                  icon = 0;
                }
#endif
                token = jx_ob_from_int(icon);            
              }
              break;
            case JX_PY_FCON:
              {
#ifdef JX_64_BIT
                double fcon;
                if( jx_os_sscanf(buffer, "%lf", &fcon) != 1) { /* use strtof instead? */
                  fcon = 0.0;
                }
#else
                float fcon; 
                if( jx_os_sscanf(buffer, "%f", &fcon) != 1) { /* use strtof instead? */
                  fcon = 0.0F;
                }
#endif
                token = jx_ob_from_float(fcon);
              }
              break;
            case JX_PY_SCON:
              buffer[st_len-1]=0;
              token = jx_ob_from_str(buffer+1);
              break;
            case JX_PY_NAME:
              token = jx_ob_from_ident(buffer);
              break;
            }
            if(buffer != stack_buffer)
              jx_free(buffer);
          }
        }
        break;
      case JX_PY_TRUE:
        token = jx_ob_from_bool(true);
        break;
      case JX_PY_FALSE:
        token = jx_ob_from_bool(false);
        break;
      case JX_PY_NONE:
        token = jx_ob_from_null();
        break;
#if 0
      case JX_PY_BUILTIN:
        token = jx_builtin_new_from_selector(0);
        break;
#endif
      case JX_PY_ERROR:
        s->context.status = JX_STATUS_SYNTAX_ERROR;
        break;
      }
    
      if(tok_type == JX_PY_EOI) {
        s->context.exhausted = JX_TRUE;
      }

      if(!skip_token) {

        s->colon_just_seen = (tok_type == JX_PY_COLON);

        jx_py_send(jx_Parser, (int)tok_type, token, &s->context);

        if(!jx_ok(s->context.status)) /* something bad happened */
          break;
        
        switch(tok_type) { 
        case JX_PY_EOI:
          {/* parse a null token to enable acceptance */
            jx_ob ob = JX_OB_NULL;
            jx_py_send(jx_Parser, 0, ob, &s->context);
          }
          break;
        }
      }
      if(s->context.status) /* accepted or complete */
        break;
      else /* we need more */
        s->n_tok_parsed++;
    }
  }
  /* free the parser instance */
  jx_py_Free(jx_Parser, jx__py_free);
}


static jx_status jx_py_scanner_state_init(jx_py_scanner_state *state)
{
  memset(state,0,sizeof(jx_py_scanner_state));
  state->indent_stack = jx_list_new();
  return JX_SUCCESS;
}

static jx_status jx_py_scanner_state_reset(jx_py_scanner_state *state)
{
  if(state->bot) 
    jx_free(state->bot);
  state->bot = NULL;
  state->tok = NULL;
  state->ptr = NULL;
  state->cur = NULL;
  state->pos = NULL;
  state->lim = NULL;
  state->top = NULL;
  state->eof = NULL;
  state->line = 0;
  state->n_tok_parsed = 0;
  state->current_indent = 0;
  state->colon_just_seen = JX_FALSE;
  state->newline_just_seen = JX_FALSE;
  jx_list_reset(state->indent_stack);
  return JX_SUCCESS;
}

static jx_status jx_py_scanner_state_purge(jx_py_scanner_state *state)
{
  jx_ob_free(state->indent_stack);
  /* free last object */
  jx_ob_free(state->context.result);
  /* free the input buffer (if using stdin) */
  switch(state->mode) {
  case JX_PY_SCANNER_MODE_FILE:
  case JX_PY_SCANNER_MODE_CONSOLE:
    if(state->bot) 
      jx_free(state->bot);
    break;
  }
  return JX_SUCCESS;
}

void jx_py_echo_stdin(void)
{
  jx_py_scanner_state state;
  jx_py_scanner_state_init(&state);
  jx_bool done = JX_FALSE;
  while(!done) {    
    jx_py_scan_input(&state);
    switch(state.context.status) {
    case JX_STATUS_SYNTAX_ERROR:
      printf("syntax error.\n");
      break;
    case JX_YES: /* accepted */
      {
        jx_ob jxon = jx_ob_to_jxon(state.context.result);
        if(state.n_tok_parsed)
          printf("%s;\n",jx_ob_as_str(&jxon));
        jx_ob_free(jxon);
      }
      state.context.result = jx_null_with_ob(state.context.result);
      break;
    case JX_FAILURE:
      done = JX_TRUE;
      break;
    }
    if(state.context.exhausted)
      done = JX_TRUE;
  }
  jx_py_scanner_state_purge(&state);
}

#define JX_PY_SCANNER_MAGIC "jxJSc"

typedef struct {
  jx_opaque_ob opaque;
  jx_py_scanner_state state;
} jx_py_scanner;

static jx_status jx_py_scanner_free(jx_py_scanner *scanner) 
{
  jx_status result = JX_FAILURE;
  jx_ob magic = jx_ob_from_str(JX_PY_SCANNER_MAGIC);
  if(jx_ob_equal(scanner->opaque.magic,magic)) {
    jx_py_scanner_state_purge(&scanner->state);
    jx_ob_free(scanner->opaque.magic);
    jx_free(scanner);
    result = JX_SUCCESS;
  }
  jx_ob_free(magic);
  return result;
}

jx_ob jx_py_scanner_new_with_file(FILE *file,jx_int flags)
{
  jx_ob result = jx_ob_from_null();
  jx_py_scanner *scanner = (jx_py_scanner*)jx_calloc(1,sizeof(jx_py_scanner));
  if(scanner) {
    if(jx_ok(jx_py_scanner_state_init(&scanner->state))) {
      scanner->opaque.magic = jx_ob_from_str(JX_PY_SCANNER_MAGIC);
      scanner->opaque.free_fn = (jx_opaque_free_fn)jx_py_scanner_free;
      scanner->state.file = file;
      scanner->state.flags = flags;
      if (isatty((int)fileno(file))) {      
        scanner->state.mode = JX_PY_SCANNER_MODE_CONSOLE;
      } else {
        scanner->state.mode = JX_PY_SCANNER_MODE_FILE;
      }
      result = jx_builtin_new_with_opaque_ob(&scanner->opaque);
    } else 
      jx_free(scanner);
  }
  return result;
}

jx_ob jx_py_scanner_get_error_message(jx_ob scanner_ob)
{
  jx_ob result = jx_ob_from_null();
  jx_ob magic = jx_ob_from_str(JX_PY_SCANNER_MAGIC);
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_py_scanner *scanner = (jx_py_scanner*)scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic,magic)) {
      jx_py_scanner_state *state = &scanner->state;
      jx_ob list = jx_list_new();
      if(JX_OK(state->context.status)) {
        jx_char buffer[50];
        sprintf(buffer,"Error: failure on or before line %d\n",(int)state->line+1);
        jx_list_append(list, jx_ob_from_str(buffer));
      } else {
        jx_char buffer[50];
        sprintf(buffer,"Error: invalid syntax on line %d\n",(int)state->line+1);
        jx_list_append(list, jx_ob_from_str(buffer));
      }
      if(state->bot != state->lim) {
        if(state->tok >= state->pos) {
          jx_list_append(list, jx_ob_from_str_with_len(state->pos, state->tok - state->pos));
        } else if(state->tok > state->bot) {
          jx_list_append(list, jx_ob_from_str_with_len(state->bot, state->tok - state->bot));
        }
        if((state->cur > state->tok) && state->tok && state->tok[0]) {
          jx_list_append(list, jx_ob_from_str(" -->"));
          jx_list_append(list, jx_ob_from_str_with_len(state->tok, state->cur - state->tok));
          jx_list_append(list, jx_ob_from_str("<-- "));
          if(state->lim > state->cur) {
            jx_char *ch = state->cur;
            while( (ch<state->lim) && (*ch!='\n') &&(*ch!='\r'))
              ch++;
            jx_list_append(list, jx_ob_from_str_with_len(state->cur, ch - state->cur));
          }
        } else {
          jx_list_append(list, jx_ob_from_str("<-- (at end of input)"));
        }
      } else {
        jx_list_append(list, jx_ob_from_str("<-- (at end of input)"));
      }
      result = jx_str_join_with_list(list);
    }
  }
  jx_ob_free(magic);
  return result;
}

jx_status jx_py_scanner_next_ob(jx_ob *result, jx_ob scanner_ob)
{
  jx_ob magic = jx_ob_from_str(JX_PY_SCANNER_MAGIC);
  jx_status status = JX_FAILURE;
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_py_scanner *scanner = (jx_py_scanner*)scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic,magic)) {
      jx_py_scanner_state *state = &scanner->state;
      state->context.status = JX_SUCCESS;
      while(!state->context.status) {    
        jx_py_scan_input(state);
        switch(state->context.status) {
        case JX_YES: /* accept called */
          if(jx_null_check(state->context.result)) {
            status = JX_NO; /* nothing of substance parsed -- keep going! */
          } else {
            jx_ob_replace(result, state->context.result);
            state->context.result = jx_ob_from_null();
            status = state->n_tok_parsed ? JX_YES : JX_NO; /* but were any tokens parsed */
          }
          break;
        default:
          status = state->context.status;
          break;
        }
        if(state->context.exhausted) {
          if(!status) 
            status = JX_STATUS_EXHAUSTED;
          break;
        }
      }
    }
  }
  jx_ob_free(magic);
  return status;
}

jx_status jx_py_scanner_purge_input(jx_ob scanner_ob)
{
  jx_ob magic = jx_ob_from_str(JX_PY_SCANNER_MAGIC);
  jx_status status = JX_FAILURE;
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_py_scanner *scanner = (jx_py_scanner*)scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic,magic)) {
      jx_py_scanner_state *state = &scanner->state;
      jx_py_scanner_state_reset(state);
      status = JX_SUCCESS;
    }
  }
  jx_ob_free(magic);
  return status;
}
