#define JX_PY_ERROR                           1
#define JX_PY_EOI                             2
#define JX_PY_NEWLINE                         3
#define JX_PY_DEF                             4
#define JX_PY_NAME                            5
#define JX_PY_COLON                           6
#define JX_PY_OPEN_PAR                        7
#define JX_PY_CLOSE_PAR                       8
#define JX_PY_OPEN_CURLY_BRACE                9
#define JX_PY_CLOSE_CURLY_BRACE              10
#define JX_PY_COMMA                          11
#define JX_PY_SEMICOLON                      12
#define JX_PY_DEL                            13
#define JX_PY_PASS                           14
#define JX_PY_RETURN                         15
#define JX_PY_PLUS_EQUALS                    16
#define JX_PY_MINUS_EQUALS                   17
#define JX_PY_EQUALS                         18
#define JX_PY_PRINT                          19
#define JX_PY_IF                             20
#define JX_PY_ELSE                           21
#define JX_PY_ELIF                           22
#define JX_PY_WHILE                          23
#define JX_PY_FOR                            24
#define JX_PY_IN                             25
#define JX_PY_INDENT                         26
#define JX_PY_DEDENT                         27
#define JX_PY_NOT                            28
#define JX_PY_LESS_THAN                      29
#define JX_PY_LESS_THAN_OR_EQ                30
#define JX_PY_EQ_EQ                          31
#define JX_PY_NOT_EQ                         32
#define JX_PY_GREATER_THAN                   33
#define JX_PY_GREATER_THAN_OR_EQ             34
#define JX_PY_PLUS                           35
#define JX_PY_MINUS                          36
#define JX_PY_ASTERISK                       37
#define JX_PY_SLASH                          38
#define JX_PY_SLASHSLASH                     39
#define JX_PY_PERCENT                        40
#define JX_PY_TILDE                          41
#define JX_PY_DOUBLE_ASTERISK                42
#define JX_PY_OPEN_RECT_BRACE                43
#define JX_PY_CLOSE_RECT_BRACE               44
#define JX_PY_ICON                           45
#define JX_PY_FCON                           46
#define JX_PY_NONE                           47
#define JX_PY_TRUE                           48
#define JX_PY_FALSE                          49
#define JX_PY_LAMBDA                         50
#define JX_PY_DOT                            51
#define JX_PY_CLASS                          52
#define JX_PY_SCON                           53
