#define JX_PY_ERROR                           1
#define JX_PY_NEWLINE                         2
#define JX_PY_DEF                             3
#define JX_PY_NAME                            4
#define JX_PY_COLON                           5
#define JX_PY_OPEN_PAR                        6
#define JX_PY_CLOSE_PAR                       7
#define JX_PY_COMMA                           8
#define JX_PY_SEMICOLON                       9
#define JX_PY_DEL                            10
#define JX_PY_PASS                           11
#define JX_PY_PLUS_EQUALS                    12
#define JX_PY_MINUS_EQUALS                   13
#define JX_PY_EQUALS                         14
#define JX_PY_PRINT                          15
#define JX_PY_ELSE                           16
#define JX_PY_ELIF                           17
#define JX_PY_IF                             18
#define JX_PY_WHILE                          19
#define JX_PY_FOR                            20
#define JX_PY_IN                             21
#define JX_PY_INDENT                         22
#define JX_PY_DEDENT                         23
#define JX_PY_NOT                            24
#define JX_PY_LESS_THAN                      25
#define JX_PY_LESS_THAN_OR_EQ                26
#define JX_PY_EQ_EQ                          27
#define JX_PY_NOT_EQ                         28
#define JX_PY_GREATER_THAN                   29
#define JX_PY_GREATER_THAN_OR_EQ             30
#define JX_PY_PLUS                           31
#define JX_PY_MINUS                          32
#define JX_PY_ASTERISK                       33
#define JX_PY_SLASH                          34
#define JX_PY_SLASHSLASH                     35
#define JX_PY_PERCENT                        36
#define JX_PY_TILDE                          37
#define JX_PY_OPEN_RECT_BRACE                38
#define JX_PY_CLOSE_RECT_BRACE               39
#define JX_PY_OPEN_CURLY_BRACE               40
#define JX_PY_CLOSE_CURLY_BRACE              41
#define JX_PY_ICON                           42
#define JX_PY_FCON                           43
#define JX_PY_LAMBDA                         44
#define JX_PY_SCON                           45
