#define JX_PY_ERROR                           1
#define JX_PY_EOI                             2
#define JX_PY_NEWLINE                         3
#define JX_PY_DEF                             4
#define JX_PY_NAME                            5
#define JX_PY_COLON                           6
#define JX_PY_OPEN_PAR                        7
#define JX_PY_CLOSE_PAR                       8
#define JX_PY_COMMA                           9
#define JX_PY_SEMICOLON                      10
#define JX_PY_DEL                            11
#define JX_PY_PASS                           12
#define JX_PY_PLUS_EQUALS                    13
#define JX_PY_MINUS_EQUALS                   14
#define JX_PY_EQUALS                         15
#define JX_PY_PRINT                          16
#define JX_PY_IF                             17
#define JX_PY_ELSE                           18
#define JX_PY_ELIF                           19
#define JX_PY_WHILE                          20
#define JX_PY_FOR                            21
#define JX_PY_IN                             22
#define JX_PY_INDENT                         23
#define JX_PY_DEDENT                         24
#define JX_PY_NOT                            25
#define JX_PY_LESS_THAN                      26
#define JX_PY_LESS_THAN_OR_EQ                27
#define JX_PY_EQ_EQ                          28
#define JX_PY_NOT_EQ                         29
#define JX_PY_GREATER_THAN                   30
#define JX_PY_GREATER_THAN_OR_EQ             31
#define JX_PY_PLUS                           32
#define JX_PY_MINUS                          33
#define JX_PY_ASTERISK                       34
#define JX_PY_SLASH                          35
#define JX_PY_SLASHSLASH                     36
#define JX_PY_PERCENT                        37
#define JX_PY_TILDE                          38
#define JX_PY_OPEN_RECT_BRACE                39
#define JX_PY_CLOSE_RECT_BRACE               40
#define JX_PY_OPEN_CURLY_BRACE               41
#define JX_PY_CLOSE_CURLY_BRACE              42
#define JX_PY_ICON                           43
#define JX_PY_FCON                           44
#define JX_PY_LAMBDA                         45
#define JX_PY_SCON                           46
