/* Generated by re2c 0.12.3 on Mon Jun  1 01:45:37 2009 */
#line 1 "jx_py_scan.re"
/* RE2C-based tokenizer */

/* 
Copyright (c) 2009, DeLano Scientific LLC, Palo Alto, California, USA.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright
 notice, this list of conditions and the following disclaimer in the
 documentation and/or other materials provided with the distribution.

* Neither the name of the DeLano Scientific LLC nor the names of its
 contributors may be used to endorse or promote products derived from
 this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#include "jx_py_private.h"

#define JX_PY_SCANNER_MODE_FILE    0 
#define JX_PY_SCANNER_MODE_STRING  1
#define JX_PY_SCANNER_MODE_CONSOLE 2

typedef struct {
  jx_char *bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
  jx_int line;
  jx_int n_tok_parsed;
  jx_int mode;
  FILE *file;
  jx_py_parse_context context;
  jx_ob indent_stack;
  jx_int current_indent;
  jx_bool newline_just_seen;
  jx_bool colon_just_seen;
  jx_bool saved_token;
} jx_py_scanner_state;

#ifndef true
#define true 1
#endif

#ifndef false
#define false 0
#endif

#define   BSIZE   8192

#define   YYCTYPE     jx_char
#define   YYCURSOR    cursor
#define   YYLIMIT     s->lim
#define   YYMARKER    s->ptr
#define   YYFILL(n)   {cursor = jx_fill(s, cursor);}

#define   RET(i)   {s->cur = cursor; return i;}

#ifndef JX_PY_EOI
#define JX_PY_EOI -1
#endif

#ifndef JX_PY_DEDENT_NEWLINE
#define JX_PY_DEDENT_NEWLINE -2
#endif

/* parser allocator */

static void *jx__py_alloc(jx_size bytes)
{
  jx_char *ptr = NULL;
  ptr = jx_calloc(1,bytes);
  return (void*)ptr;
}

static void jx__py_free(void *ptr)
{
  if(ptr) 
    jx_free(ptr);
}

static jx_size jx_read_file(FILE *file, jx_char *buf, jx_size buf_size, jx_int mode)
{
  switch(mode) {
  case JX_PY_SCANNER_MODE_FILE:
    return fread((char*)buf, 1, buf_size, file);
    break;
  case JX_PY_SCANNER_MODE_CONSOLE:
    if(fgets((char*)buf, buf_size, file)) {
      return jx_strlen(buf);
    } else 
      return 0;
    break;
  }
  return 0;
}

static jx_char *jx_fill(jx_py_scanner_state *s, jx_char *cursor)
{
  switch(s->mode) {
  case JX_PY_SCANNER_MODE_FILE:
  case JX_PY_SCANNER_MODE_CONSOLE:
    if(!s->eof) { /* only fill if eof is not set (known) */
      jx_diff cnt = s->tok - s->bot; /* amount of open space in buffer */
      if(cnt) {
        if(s->lim > s->tok) { /* any remaining characters? */
          jx_os_memcpy(s->bot, s->tok, s->lim - s->tok); /* move to start of buffer */
        }
        s->tok = s->bot;  /* shift pointers accordingly */
        s->ptr -= cnt; 
        cursor -= cnt;
        s->pos -= cnt;
        s->lim -= cnt;
      }
      if((s->top - s->lim) < BSIZE) { /* open space less than read quantum? */
        /* allocate a larger buffer */
        jx_char *buf = (jx_char*) jx_calloc(1,((s->lim - s->bot) +
                                               BSIZE)*sizeof(jx_char));
        if(buf) { /* and copy contents to new buffer */
          jx_os_memcpy(buf, s->tok, s->lim - s->tok);
          s->tok = buf; /* adjust pointers accordingly */
          s->ptr = &buf[s->ptr - s->bot];
          cursor = &buf[cursor - s->bot];
          s->pos = &buf[s->pos - s->bot];
          s->lim = &buf[s->lim - s->bot];
          s->top = &s->lim[BSIZE];
          if(s->bot) { /* free old buffer (if exists) */
            jx_free(s->bot);
          }
          s->bot = buf; /* use the new buffer from now on */
        }
      }
      if((s->top - s->lim) < BSIZE) {
        /* unhandled error condition */
      } else {
        cnt = jx_read_file(s->file, s->lim, BSIZE, s->mode);
        if(cnt != BSIZE) {
          jx_size cc = cnt;
          while(cc<BSIZE) {
            s->lim[cc] = 0;
            cc++;
          }
          s->eof = &s->lim[cnt]; 
          if(cnt) { /* short read ...there may be more to come */
            s->eof++; 
          } else { /* nothing read, so set the null sentinel */
            *(s->eof) = 0;
          }
        }
        s->lim += cnt;
      }
    }
    break;
  }
  return cursor;
}
  
static int jx_scan(jx_py_scanner_state *s)
{
  jx_char *cursor = s->cur;
 std:
  s->tok = cursor;
  
  
#line 182 "<stdout>"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if((YYLIMIT - YYCURSOR) < 7) YYFILL(7);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:	goto yy62;
	case 0x09:
	case 0x0B:
	case 0x0C:
	case ' ':	goto yy56;
	case 0x0A:	goto yy60;
	case '!':	goto yy47;
	case '"':	goto yy16;
	case '#':	goto yy58;
	case '%':	goto yy41;
	case '\'':	goto yy17;
	case '(':	goto yy23;
	case ')':	goto yy25;
	case '*':	goto yy37;
	case '+':	goto yy33;
	case ',':	goto yy54;
	case '-':	goto yy35;
	case '.':	goto yy14;
	case '/':	goto yy39;
	case '0':	goto yy11;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy13;
	case ':':	goto yy50;
	case ';':	goto yy52;
	case '<':	goto yy43;
	case '=':	goto yy45;
	case '>':	goto yy48;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'g':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'o':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy18;
	case '[':	goto yy19;
	case ']':	goto yy21;
	case 'd':	goto yy9;
	case 'e':	goto yy4;
	case 'f':	goto yy7;
	case 'i':	goto yy2;
	case 'l':	goto yy10;
	case 'n':	goto yy5;
	case 'p':	goto yy6;
	case 'w':	goto yy8;
	case '{':	goto yy27;
	case '}':	goto yy29;
	case '~':	goto yy31;
	default:	goto yy64;
	}
yy2:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'f':	goto yy183;
	case 'n':	goto yy185;
	default:	goto yy84;
	}
yy3:
#line 213 "jx_py_scan.re"
	{ RET(JX_PY_NAME); }
#line 295 "<stdout>"
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'l':	goto yy176;
	default:	goto yy84;
	}
yy5:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'o':	goto yy173;
	default:	goto yy84;
	}
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'a':	goto yy164;
	case 'r':	goto yy165;
	default:	goto yy84;
	}
yy7:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'o':	goto yy161;
	default:	goto yy84;
	}
yy8:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'h':	goto yy156;
	default:	goto yy84;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'e':	goto yy151;
	default:	goto yy84;
	}
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'a':	goto yy145;
	default:	goto yy84;
	}
yy11:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy121;
	case 'X':
	case 'x':	goto yy138;
	default:	goto yy137;
	}
yy12:
#line 205 "jx_py_scan.re"
	{ RET(JX_PY_ICON); }
#line 361 "<stdout>"
yy13:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy119;
yy14:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy109;
	default:	goto yy15;
	}
yy15:
#line 270 "jx_py_scan.re"
	{
#ifdef JX_PY_PARSER_DEBUG
      printf("unexpected character: %c\n", *s->tok);
#endif
       RET(JX_PY_ERROR);
    }
#line 389 "<stdout>"
yy16:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy15;
	default:	goto yy100;
	}
yy17:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy15;
	default:	goto yy90;
	}
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy84;
yy19:
	++YYCURSOR;
#line 215 "jx_py_scan.re"
	{ RET(JX_PY_OPEN_RECT_BRACE); }
#line 414 "<stdout>"
yy21:
	++YYCURSOR;
#line 216 "jx_py_scan.re"
	{ RET(JX_PY_CLOSE_RECT_BRACE); }
#line 419 "<stdout>"
yy23:
	++YYCURSOR;
#line 218 "jx_py_scan.re"
	{ RET(JX_PY_OPEN_PAR); }
#line 424 "<stdout>"
yy25:
	++YYCURSOR;
#line 219 "jx_py_scan.re"
	{ RET(JX_PY_CLOSE_PAR); }
#line 429 "<stdout>"
yy27:
	++YYCURSOR;
#line 221 "jx_py_scan.re"
	{ RET(JX_PY_OPEN_CURLY_BRACE); }
#line 434 "<stdout>"
yy29:
	++YYCURSOR;
#line 222 "jx_py_scan.re"
	{ RET(JX_PY_CLOSE_CURLY_BRACE); }
#line 439 "<stdout>"
yy31:
	++YYCURSOR;
#line 224 "jx_py_scan.re"
	{ RET(JX_PY_TILDE); }
#line 444 "<stdout>"
yy33:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy81;
	default:	goto yy34;
	}
yy34:
#line 225 "jx_py_scan.re"
	{ RET(JX_PY_PLUS); }
#line 454 "<stdout>"
yy35:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy79;
	default:	goto yy36;
	}
yy36:
#line 226 "jx_py_scan.re"
	{ RET(JX_PY_MINUS); }
#line 464 "<stdout>"
yy37:
	++YYCURSOR;
#line 228 "jx_py_scan.re"
	{ RET(JX_PY_ASTERISK); }
#line 469 "<stdout>"
yy39:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '/':	goto yy77;
	default:	goto yy40;
	}
yy40:
#line 229 "jx_py_scan.re"
	{ RET(JX_PY_SLASH); }
#line 479 "<stdout>"
yy41:
	++YYCURSOR;
#line 231 "jx_py_scan.re"
	{ RET(JX_PY_PERCENT); }
#line 484 "<stdout>"
yy43:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy75;
	case '>':	goto yy73;
	default:	goto yy44;
	}
yy44:
#line 233 "jx_py_scan.re"
	{ RET(JX_PY_LESS_THAN); }
#line 495 "<stdout>"
yy45:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy71;
	default:	goto yy46;
	}
yy46:
#line 241 "jx_py_scan.re"
	{ RET(JX_PY_EQUALS); }
#line 505 "<stdout>"
yy47:
	yych = *++YYCURSOR;
	switch(yych) {
	case '=':	goto yy69;
	default:	goto yy15;
	}
yy48:
	++YYCURSOR;
	switch((yych = *YYCURSOR)) {
	case '=':	goto yy67;
	default:	goto yy49;
	}
yy49:
#line 238 "jx_py_scan.re"
	{ RET(JX_PY_GREATER_THAN); }
#line 521 "<stdout>"
yy50:
	++YYCURSOR;
#line 246 "jx_py_scan.re"
	{ RET(JX_PY_COLON); }
#line 526 "<stdout>"
yy52:
	++YYCURSOR;
#line 248 "jx_py_scan.re"
	{ RET(JX_PY_SEMICOLON); }
#line 531 "<stdout>"
yy54:
	++YYCURSOR;
#line 250 "jx_py_scan.re"
	{ RET(JX_PY_COMMA); }
#line 536 "<stdout>"
yy56:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy66;
yy57:
#line 252 "jx_py_scan.re"
	{ if(s->pos == s->tok) 
                    s->current_indent = cursor - s->pos;
                  goto std; }
#line 546 "<stdout>"
yy58:
	++YYCURSOR;
#line 256 "jx_py_scan.re"
	{ goto comment; }
#line 551 "<stdout>"
yy60:
	++YYCURSOR;
#line 258 "jx_py_scan.re"
	{
    s->line++;
    s->pos = cursor;
    s->eof = NULL;
    RET(JX_PY_NEWLINE);
  }
#line 561 "<stdout>"
yy62:
	++YYCURSOR;
#line 265 "jx_py_scan.re"
	{ 
      if(cursor == s->eof) RET(JX_PY_EOI);
      RET(JX_PY_EOI); 
    }
#line 569 "<stdout>"
yy64:
	yych = *++YYCURSOR;
	goto yy15;
yy65:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy66:
	switch(yych) {
	case 0x09:
	case 0x0B:
	case 0x0C:
	case ' ':	goto yy65;
	default:	goto yy57;
	}
yy67:
	++YYCURSOR;
#line 239 "jx_py_scan.re"
	{ RET(JX_PY_GREATER_THAN_OR_EQ); }
#line 589 "<stdout>"
yy69:
	++YYCURSOR;
#line 236 "jx_py_scan.re"
	{ RET(JX_PY_NOT_EQ); }
#line 594 "<stdout>"
yy71:
	++YYCURSOR;
#line 235 "jx_py_scan.re"
	{ RET(JX_PY_EQ_EQ); }
#line 599 "<stdout>"
yy73:
	++YYCURSOR;
#line 237 "jx_py_scan.re"
	{ RET(JX_PY_NOT_EQ); }
#line 604 "<stdout>"
yy75:
	++YYCURSOR;
#line 234 "jx_py_scan.re"
	{ RET(JX_PY_LESS_THAN_OR_EQ); }
#line 609 "<stdout>"
yy77:
	++YYCURSOR;
#line 230 "jx_py_scan.re"
	{ RET(JX_PY_SLASHSLASH); }
#line 614 "<stdout>"
yy79:
	++YYCURSOR;
#line 244 "jx_py_scan.re"
	{ RET(JX_PY_MINUS_EQUALS); }
#line 619 "<stdout>"
yy81:
	++YYCURSOR;
#line 243 "jx_py_scan.re"
	{ RET(JX_PY_PLUS_EQUALS); }
#line 624 "<stdout>"
yy83:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy84:
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy3;
	}
yy85:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy87;
	default:	goto yy86;
	}
yy86:
	YYCURSOR = YYMARKER;
	switch(yyaccept) {
	case 0: 	goto yy3;
	case 1: 	goto yy12;
	case 2: 	goto yy15;
	case 3: 	goto yy111;
	case 4: 	goto yy150;
	case 5: 	goto yy153;
	case 6: 	goto yy155;
	case 7: 	goto yy160;
	case 8: 	goto yy163;
	case 9: 	goto yy169;
	case 10: 	goto yy172;
	case 11: 	goto yy175;
	case 12: 	goto yy180;
	case 13: 	goto yy182;
	case 14: 	goto yy184;
	case 15: 	goto yy186;
	}
yy87:
	yyaccept = 0;
	YYMARKER = ++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy87;
	default:	goto yy3;
	}
yy89:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy90:
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy86;
	case '\'':	goto yy92;
	case '\\':	goto yy91;
	default:	goto yy89;
	}
yy91:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy89;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy95;
	case 'x':	goto yy94;
	default:	goto yy86;
	}
yy92:
	++YYCURSOR;
#line 211 "jx_py_scan.re"
	{ RET(JX_PY_SCON); }
#line 893 "<stdout>"
yy94:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy97;
	default:	goto yy86;
	}
yy95:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy86;
	case '\'':	goto yy92;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy95;
	case '\\':	goto yy91;
	default:	goto yy89;
	}
yy97:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy86;
	case '\'':	goto yy92;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy97;
	case '\\':	goto yy91;
	default:	goto yy89;
	}
yy99:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy100:
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy86;
	case '"':	goto yy102;
	case '\\':	goto yy101;
	default:	goto yy99;
	}
yy101:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy99;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy105;
	case 'x':	goto yy104;
	default:	goto yy86;
	}
yy102:
	++YYCURSOR;
#line 209 "jx_py_scan.re"
	{ RET(JX_PY_SCON); }
#line 1018 "<stdout>"
yy104:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy107;
	default:	goto yy86;
	}
yy105:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy86;
	case '"':	goto yy102;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy105;
	case '\\':	goto yy101;
	default:	goto yy99;
	}
yy107:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:
	case 0x0A:	goto yy86;
	case '"':	goto yy102;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy107;
	case '\\':	goto yy101;
	default:	goto yy99;
	}
yy109:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy109;
	case 'E':
	case 'e':	goto yy112;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy113;
	default:	goto yy111;
	}
yy111:
#line 207 "jx_py_scan.re"
	{ RET(JX_PY_FCON); }
#line 1127 "<stdout>"
yy112:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy114;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy115;
	default:	goto yy86;
	}
yy113:
	yych = *++YYCURSOR;
	goto yy111;
yy114:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy115;
	default:	goto yy86;
	}
yy115:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy115;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy113;
	default:	goto yy111;
	}
yy117:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'E':
	case 'e':	goto yy128;
	default:	goto yy127;
	}
yy118:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy119:
	switch(yych) {
	case '.':	goto yy117;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy118;
	case 'E':
	case 'e':	goto yy120;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy121;
	default:	goto yy12;
	}
yy120:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy123;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy124;
	default:	goto yy86;
	}
yy121:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy121;
	default:	goto yy12;
	}
yy123:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy124;
	default:	goto yy86;
	}
yy124:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy124;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy113;
	default:	goto yy111;
	}
yy126:
	yyaccept = 3;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy127:
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy126;
	case 'E':
	case 'e':	goto yy132;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy113;
	default:	goto yy111;
	}
yy128:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy129;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy130;
	default:	goto yy86;
	}
yy129:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy130;
	default:	goto yy86;
	}
yy130:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy130;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy113;
	default:	goto yy111;
	}
yy132:
	yych = *++YYCURSOR;
	switch(yych) {
	case '+':
	case '-':	goto yy133;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy134;
	default:	goto yy86;
	}
yy133:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy134;
	default:	goto yy86;
	}
yy134:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy134;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy113;
	default:	goto yy111;
	}
yy136:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy137:
	switch(yych) {
	case '.':	goto yy117;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy136;
	case 'E':
	case 'e':	goto yy120;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy143;
	default:	goto yy12;
	}
yy138:
	yych = *++YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy139;
	default:	goto yy86;
	}
yy139:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy139;
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy141;
	default:	goto yy12;
	}
yy141:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy141;
	default:	goto yy12;
	}
yy143:
	++YYCURSOR;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 'L':
	case 'U':
	case 'l':
	case 'u':	goto yy143;
	default:	goto yy12;
	}
yy145:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'm':	goto yy146;
	default:	goto yy84;
	}
yy146:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'b':	goto yy147;
	default:	goto yy84;
	}
yy147:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'd':	goto yy148;
	default:	goto yy84;
	}
yy148:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'a':	goto yy149;
	default:	goto yy84;
	}
yy149:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy150;
	}
yy150:
#line 203 "jx_py_scan.re"
	{ RET(JX_PY_LAMBDA);}
#line 1622 "<stdout>"
yy151:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'f':	goto yy154;
	case 'l':	goto yy152;
	default:	goto yy84;
	}
yy152:
	yyaccept = 5;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy153;
	}
yy153:
#line 200 "jx_py_scan.re"
	{ RET(JX_PY_DEL); }
#line 1704 "<stdout>"
yy154:
	yyaccept = 6;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy155;
	}
yy155:
#line 202 "jx_py_scan.re"
	{ RET(JX_PY_DEF); }
#line 1778 "<stdout>"
yy156:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'i':	goto yy157;
	default:	goto yy84;
	}
yy157:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'l':	goto yy158;
	default:	goto yy84;
	}
yy158:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'e':	goto yy159;
	default:	goto yy84;
	}
yy159:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy160;
	}
yy160:
#line 199 "jx_py_scan.re"
	{ RET(JX_PY_WHILE); }
#line 1873 "<stdout>"
yy161:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'r':	goto yy162;
	default:	goto yy84;
	}
yy162:
	yyaccept = 8;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy163;
	}
yy163:
#line 198 "jx_py_scan.re"
	{ RET(JX_PY_FOR); }
#line 1954 "<stdout>"
yy164:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 's':	goto yy170;
	default:	goto yy84;
	}
yy165:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'i':	goto yy166;
	default:	goto yy84;
	}
yy166:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'n':	goto yy167;
	default:	goto yy84;
	}
yy167:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 't':	goto yy168;
	default:	goto yy84;
	}
yy168:
	yyaccept = 9;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy169;
	}
yy169:
#line 197 "jx_py_scan.re"
	{ RET(JX_PY_PRINT); }
#line 2056 "<stdout>"
yy170:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 's':	goto yy171;
	default:	goto yy84;
	}
yy171:
	yyaccept = 10;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy172;
	}
yy172:
#line 201 "jx_py_scan.re"
	{ RET(JX_PY_PASS); }
#line 2137 "<stdout>"
yy173:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 't':	goto yy174;
	default:	goto yy84;
	}
yy174:
	yyaccept = 11;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy175;
	}
yy175:
#line 196 "jx_py_scan.re"
	{ RET(JX_PY_NOT);}
#line 2218 "<stdout>"
yy176:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'i':	goto yy177;
	case 's':	goto yy178;
	default:	goto yy84;
	}
yy177:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'f':	goto yy181;
	default:	goto yy84;
	}
yy178:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case 'e':	goto yy179;
	default:	goto yy84;
	}
yy179:
	yyaccept = 12;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy180;
	}
yy180:
#line 194 "jx_py_scan.re"
	{ RET(JX_PY_ELSE); }
#line 2314 "<stdout>"
yy181:
	yyaccept = 13;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy182;
	}
yy182:
#line 193 "jx_py_scan.re"
	{ RET(JX_PY_ELIF); }
#line 2388 "<stdout>"
yy183:
	yyaccept = 14;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy184;
	}
yy184:
#line 192 "jx_py_scan.re"
	{ RET(JX_PY_IF); }
#line 2462 "<stdout>"
yy185:
	yyaccept = 15;
	yych = *(YYMARKER = ++YYCURSOR);
	switch(yych) {
	case '.':	goto yy85;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy83;
	default:	goto yy186;
	}
yy186:
#line 195 "jx_py_scan.re"
	{ RET(JX_PY_IN);}
#line 2536 "<stdout>"
}
#line 277 "jx_py_scan.re"


comment:
  
#line 2543 "<stdout>"
{
	YYCTYPE yych;
	if(YYLIMIT == YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch(yych) {
	case 0x00:	goto yy189;
	case 0x0A:	goto yy190;
	default:	goto yy192;
	}
yy189:
yy190:
	++YYCURSOR;
#line 282 "jx_py_scan.re"
	{ 
      s->pos = cursor; s->line++;
      s->eof = NULL;
      goto std; 
    }
#line 2562 "<stdout>"
yy192:
	++YYCURSOR;
#line 289 "jx_py_scan.re"
	{ goto comment; }
#line 2567 "<stdout>"
}
#line 290 "jx_py_scan.re"

  
}


  /* not used:


#if 0
    "and"    { RET(JX_PY_AND); }
    "break"  { RET(JX_PY_BREAK); }
    "class"  { RET(JX_PY_CLASS); }

    "exec"   { RET(JX_PY_EXEC); }
    "from"   { RET(JX_PY_FROM); }
    "import" { RET(JX_PY_IMPORT); }
    "is"     { RET(JX_PY_IS);}
    "or"     { RET(JX_PY_OR);}
    "return" { RET(JX_PY_RETURN); }
#endif

    ("0" [xX] H+ IS?) | ("0" D+ IS?) | ([+\-]? D+ IS?) { RET(JX_PY_ICON); }

    ([+\-]? D+ E FS?) | ([+\-]? D* "." D+ E? FS?) | ([+\-]? D+ "." D* E? FS?)  { RET(JX_PY_FCON); }

    "`" (L|D|":")+  { RET(JX_PY_BUILTIN); }
    

    "-="        { RET(JX_PY_MINUS_EQUALS); }
    "*="        { RET(JX_PY_ASTERISK_EQUALS); }
    "/="        { RET(JX_PY_SLASH_EQUALS); } 
    "%="        { RET(JX_PY_PERCENT_EQUALS); } 
    "&="        { RET(JX_PY_AND_EQUALS); } 
    "|="        { RET(JX_PY_OR_EQUALS); }
    "^="        { RET(JX_PY_CARAT_EQUALS); }
    "<<="       { RET(JX_PY_LSHFT_EQUALS); }
    ">>="       { RET(JX_PY_RSHFT_QUALS); }
    "**="       { RET(JX_PY_STARSTAR_EQUALS); } 
    "//="       { RET(JX_PY_SLASHSLASH_EQUALS); } 


    "true"      { RET(JX_PY_TRUE); }
    "false"     { RET(JX_PY_FALSE); }
    "null"      { RET(JX_PY_NULL); }
    
    "."         { RET(JX_PY_DOT); }
    "`"         { RET(JX_PY_BACKAPOSTROPHE); }



    "*"         { RET(JX_PY_ASTERISK); }
    "/"         { RET(JX_PY_SLASH); }
    "%"         { RET(JX_PY_PERCENT); }
    (['] (ESC|any\[\n\\'])* [']) { RET(JX_PY_SCON); }

   */
#define SSCANF_BUFSIZE 32

/* anticipated use cases:
   (1) parsing a string buffer from memory
   (2) parsing from a file or file descriptor (e.g. stdin) 
   (3) parsing from a character stream 
*/

JX_INLINE void jx_py_send(void *parser, int token, jx_ob ob, jx_py_parse_context *context)
{
#ifdef JX_PY_PARSER_DEBUG
  printf("scanner: sending %d\n",token);
#endif
  jx_py_(parser,token, ob, context);
}


static void jx_py_scan_input(jx_py_scanner_state *s)
{
  /* allocate parser */

  void *jx_Parser = jx_py_Alloc( (void *(*)(size_t))jx__py_alloc);
  jx_int tok_type = 0;
  jx_char stack_buffer[SSCANF_BUFSIZE];

  s->context.status = 0;
  s->n_tok_parsed = 0;
  
  while(!s->context.exhausted) {
    jx_bool skip_token = JX_FALSE;
    jx_bool indent_just_changed = JX_FALSE;
    if(!s->saved_token) 
      tok_type = jx_scan(s);
    else {
      tok_type = s->saved_token;
      s->saved_token = 0;
#ifdef JX_PY_PARSER_DEBUG
    printf("scanner: saved token index %d: \n",tok_type);
#endif
    }
#ifdef JX_PY_PARSER_DEBUG
    printf("scanner: token index %d: \n",tok_type);
    jx_jxon_dump(stdout,"scanner: indent_stack",s->indent_stack);
    printf("scanner: current_indent %d\n",s->current_indent);
    printf("scanner: newline_just_seen %d\n",s->newline_just_seen);
    printf("scanner: colon_just_seen %d\n",s->colon_just_seen);
    printf("scanner: expected indent %d\n",jx_ob_as_int(jx_list_borrow(s->indent_stack,-1)));
#endif
    /* Python / block indentation handling - UGH - COMPLEX!!! */

    if(s->newline_just_seen) { /* previous token was a newline... */
      jx_int expected_indent = jx_ob_as_int(jx_list_borrow(s->indent_stack,-1));
      switch(tok_type) {
      case JX_PY_NEWLINE:
        /* current token is also a newline --  what are the implications? */
        switch(s->mode) {
        case JX_PY_SCANNER_MODE_CONSOLE:
          { /* on the console, changes in indentation are always significant */
            if(expected_indent != s->current_indent) {
              if(s->current_indent > expected_indent) {
                jx_list_push(s->indent_stack,jx_ob_from_int(s->current_indent));
                jx_py_send(jx_Parser, JX_PY_INDENT, jx_ob_from_null(),&s->context);
                indent_just_changed = JX_TRUE;
              } else if(s->current_indent < expected_indent) {


                jx_list_pop(s->indent_stack);
                expected_indent = jx_ob_as_int(jx_list_borrow(s->indent_stack,-1));
                if(expected_indent != s->current_indent) {
                  s->context.status = JX_STATUS_SYNTAX_ERROR;
                } else {
                  jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(),&s->context); 
                  jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);        
                  indent_just_changed = JX_TRUE;
                }
              }
            }
          }
          break;
        default:
          
          /* in files, changed to invisible indentation in front of
             newlines doesn't mean anything, so just ignore indentation for now */
          s->current_indent = 0; 
          break;
        }
        break;
      case JX_PY_EOI: /* end of input reached -- back-out the indents... */
        while(jx_list_size(s->indent_stack)) {
          jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(), &s->context);        
          jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);        
          jx_list_pop(s->indent_stack);
          indent_just_changed = JX_TRUE;
        }
        break;
      default: 
        {
          /* current token not a newline, so this is for real in all cases  */

          if(expected_indent != s->current_indent) {
            if(s->current_indent > expected_indent) {
              jx_list_push(s->indent_stack,jx_ob_from_int(s->current_indent));
              jx_py_send(jx_Parser, JX_PY_INDENT, jx_ob_from_null(), &s->context);
              indent_just_changed = JX_TRUE;
            } else {
              while(s->current_indent < expected_indent) {
                jx_list_pop(s->indent_stack);
                expected_indent = jx_ob_as_int(jx_list_borrow(s->indent_stack,-1));
                jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(), &s->context); 
                switch(tok_type) {
                case JX_PY_ELIF:
                case JX_PY_ELSE:
                  break;
                default:
                  jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);
                  break;
                }
                indent_just_changed = JX_TRUE;
                if(expected_indent == s->current_indent) {
                  break;
                }
              }
              if(expected_indent != s->current_indent) {
                s->context.status = JX_STATUS_SYNTAX_ERROR;
                break;
              } else if(!s->current_indent) {
                switch(tok_type) {
                case JX_PY_ELIF:
                case JX_PY_ELSE:
                  break;
                default:
                  jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context); 
                  break;
                }
              }
            }
          }
        }
        break;
      }
    } else { /* previous token was not a newline */
      switch(tok_type) {
      case JX_PY_EOI: /* end of input reached -- back-out the indents... */
        while(jx_list_size(s->indent_stack)) {
          jx_py_send(jx_Parser, JX_PY_DEDENT, jx_ob_from_null(), &s->context);        
          jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);        
          jx_list_pop(s->indent_stack);
          indent_just_changed = JX_TRUE;
        }
        break;
      }
    }

    /* address newline subtleties... */

    if(tok_type == JX_PY_NEWLINE) {
      if(s->newline_just_seen && (!indent_just_changed) && (!s->colon_just_seen)) {
        /* suppress extra newlines which don't change the indent level */
        skip_token = true;
      } else if (!s->n_tok_parsed++) {
        /* skip leading newlines in parse block */
        skip_token = true;
      } else if((!s->colon_just_seen) && 
                (!jx_list_size(s->indent_stack) || (s->newline_just_seen))) {
        /* help parser along */                             
        jx_py_send(jx_Parser, JX_PY_NEWLINE, jx_ob_from_null(), &s->context);                
      }
    }
    s->newline_just_seen = (tok_type == JX_PY_NEWLINE); /* for next time */

    if(s->newline_just_seen)
      s->current_indent = 0;

    if(s->context.status) {/* accepted or complete */
      s->saved_token = tok_type;
      break;
    }

    {
      jx_ob token = JX_OB_NULL;
      jx_size st_len = s->cur - s->tok;
      
#ifdef JX_PY_PARSER_DEBUG
      {
        jx_size i;
        jx_char *c = s->tok;
        
        printf("scanner: token: '");
        if(st_len) {
          for(i=0;i<st_len;i++) {
            printf("%c",*(c++));
          }
        }
        printf("'\n");
      }
#endif

      switch(tok_type) {
      case JX_PY_ICON:
      case JX_PY_FCON:
      case JX_PY_SCON:
      case JX_PY_NAME:
        {
          char *buffer = stack_buffer;
          if(st_len >= SSCANF_BUFSIZE) {
            buffer = jx_malloc(st_len+1);
          }
          if(buffer) {
            jx_os_strncpy(buffer, s->tok, st_len);                              
            buffer[st_len] = 0;
            switch(tok_type) {
            case JX_PY_ICON:
              {
#ifdef JX_64_BIT
                jx_int icon;
                if( jx_os_sscanf(buffer, "%lli", &icon) != 1) { /* use strtol instead? */
                  icon = 0;
                }
                token = jx_ob_from_int(icon);            
#else
                int icon;
                if( jx_os_sscanf(buffer, "%i", &icon) != 1) { /* use strtol instead? */
                  icon = 0;
                }
#endif
                token = jx_ob_from_int(icon);            
              }
              break;
            case JX_PY_FCON:
              {
#ifdef JX_64_BIT
                double fcon;
                if( jx_os_sscanf(buffer, "%lf", &fcon) != 1) { /* use strtof instead? */
                  fcon = 0.0;
                }
#else
                float fcon; 
                if( jx_os_sscanf(buffer, "%f", &fcon) != 1) { /* use strtof instead? */
                  fcon = 0.0F;
                }
#endif
                token = jx_ob_from_float(fcon);
              }
              break;
            case JX_PY_SCON:
              buffer[st_len-1]=0;
              token = jx_ob_from_str(buffer+1);
              break;
            case JX_PY_NAME:
              token = jx_ob_from_ident(buffer);
              break;
            }
            if(buffer != stack_buffer)
              jx_free(buffer);
          }
        }
        break;
#if 0
      case JX_PY_TRUE:
        token = jx_ob_from_bool(true);
        break;
      case JX_PY_FALSE:
        token = jx_ob_from_bool(false);
        break;
      case JX_PY_NULL:
        token = jx_ob_from_null();
        break;
      case JX_PY_BUILTIN:
        token = jx_builtin_new_from_selector(0);
        break;
#endif
      case JX_PY_ERROR:
        s->context.status = JX_STATUS_SYNTAX_ERROR;
        break;
      }
    
      if(tok_type == JX_PY_EOI) {
        s->context.exhausted = JX_TRUE;
      }

      if(!skip_token) {

        s->colon_just_seen = (tok_type == JX_PY_COLON);

        jx_py_send(jx_Parser, (int)tok_type, token, &s->context);

        if(!jx_ok(s->context.status)) /* something bad happened */
          break;
        
        switch(tok_type) { 
        case JX_PY_EOI:
          {/* parse a null token to enable acceptance */
            jx_ob ob = JX_OB_NULL;
            jx_py_send(jx_Parser, 0, ob, &s->context);
          }
          break;
        }
      }
      if(s->context.status) /* accepted or complete */
        break;
      else /* we need more */
        s->n_tok_parsed++;
    }
  }
  /* free the parser instance */
  jx_py_Free(jx_Parser, jx__py_free);
}

#if 0
static void jx_py_scan_input(jx_py_scanner_state *state)
{
  /* allocate parser */

  void *jx_Parser = jx_py_Alloc( (void *(*)(size_t))jx__py_alloc);
  jx_int tok_type = 0;
  jx_char stack_buffer[SSCANF_BUFSIZE];
  jx_int colon_seen = JX_FALSE;
  jx_int newline_seen = JX_FALSE;
  s->context.status = 0;
  s->n_tok_parsed = 0;

  while(!s->context.exhausted) {
    tok_type = jx_scan(state);
    {
      jx_ob token = JX_OB_NULL;
      jx_size st_len = s->cur - s->tok;
      jx_bool skip = JX_FALSE;
      
#ifdef JX_PY_PARSER_DEBUG
      
      if(1) {
        jx_size i;
        jx_char *c = s->tok;

        printf("token type %d: ",tok_type);
        
        if(st_len) {
          for(i=0;i<st_len;i++) {
            printf("%c",*(c++));
          }
          printf("\n");
        }
      }
#endif

      switch(tok_type) {
      case JX_PY_INDENT:
      case JX_PY_DEDENT:
      case JX_PY_NEWLINE:
        break;
      default:
        if(newline_seen && 
           (s->indent_level)) {
          int new_indent = (s->tok - s->pos);
          if(new_indent != s->indent_level) {
            jx_ob ob = jx_ob_from_null();
            jx_py_(jx_Parser, JX_PY_DEDENT, ob, &s->context);        
            s->indent_level = new_indent;
          }
        }
      }

      switch(tok_type) {
      case JX_PY_ICON:
      case JX_PY_FCON:
      case JX_PY_SCON:
      case JX_PY_NAME:
        {
          char *buffer = stack_buffer;
          if(st_len >= SSCANF_BUFSIZE) {
            buffer = jx_malloc(st_len+1);
          }
          if(buffer) {
            jx_os_strncpy(buffer, s->tok, st_len);                              
            buffer[st_len] = 0;
            switch(tok_type) {
            case JX_PY_ICON:
              {
#ifdef JX_64_BIT
                jx_int icon;
                if( jx_os_sscanf(buffer, "%lli", &icon) != 1) { /* use strtol instead? */
                  icon = 0;
                }
                token = jx_ob_from_int(icon);            
#else
                int icon;
                if( jx_os_sscanf(buffer, "%i", &icon) != 1) { /* use strtol instead? */
                  icon = 0;
                }
#endif
                token = jx_ob_from_int(icon);            
              }
              break;
            case JX_PY_FCON:
              {
#ifdef JX_64_BIT
                double fcon;
                if( jx_os_sscanf(buffer, "%lf", &fcon) != 1) { /* use strtof instead? */
                  fcon = 0.0;
                }
#else
                float fcon; 
                if( jx_os_sscanf(buffer, "%f", &fcon) != 1) { /* use strtof instead? */
                  fcon = 0.0F;
                }
#endif
                token = jx_ob_from_float(fcon);
              }
              break;
            case JX_PY_SCON:
              buffer[st_len-1]=0;
              token = jx_ob_from_str(buffer+1);
              break;
            case JX_PY_NAME:
              token = jx_ob_from_ident(buffer);
              break;
            }
            if(buffer != stack_buffer)
              jx_free(buffer);
          }
        }
        break;
#if 0
      case JX_PY_TRUE:
        token = jx_ob_from_bool(true);
        break;
      case JX_PY_FALSE:
        token = jx_ob_from_bool(false);
        break;
      case JX_PY_NULL:
        token = jx_ob_from_null();
        break;
      case JX_PY_BUILTIN:
        token = jx_builtin_new_from_selector(0);
        break;
#endif
      case JX_PY_DEDENT_NEWLINE:
        {
          jx_ob ob = jx_ob_from_null();
          jx_py_(jx_Parser, JX_PY_DEDENT, ob, &s->context);        
          tok_type = JX_PY_NEWLINE;
          jx_py_(jx_Parser, JX_PY_NEWLINE, ob, &s->context);        
          tok_type = JX_PY_NEWLINE;
        }
        break;
      case JX_PY_NEWLINE:
        if((!colon_seen)&&(!s->indent_level)) { /* send double newline */
          jx_ob ob = jx_ob_from_null();
          jx_py_(jx_Parser, JX_PY_NEWLINE, ob, &s->context);        
          tok_type = JX_PY_NEWLINE;
        }
        break;
      case JX_PY_ERROR:
        s->context.status = JX_STATUS_SYNTAX_ERROR;
        break;
      case JX_PY_EOI:
        skip = JX_TRUE;
        break;
      }
      
      newline_seen = (tok_type == JX_PY_NEWLINE);

      if(!skip) {
        colon_seen = (tok_type == JX_PY_COLON);
        jx_py_(jx_Parser, (int)tok_type, token, &s->context);
        
        if(!jx_ok(s->context.status)) /* something bad happened */
          break;
      }
      switch(tok_type) {
      case JX_PY_EOI:
        {/* parse a null token to enable acceptance */
          jx_ob ob = JX_OB_NULL;
          jx_py_(jx_Parser, 0, ob, &s->context);
        }
        break;
      }
      
      if(s->context.status) /* accepted or complete */
        break;
      else
        s->n_tok_parsed++;
    }
  
    if(tok_type == JX_PY_EOI) {
      s->context.exhausted = JX_TRUE;
    }
  }
  
  /* free the parser instance */
  jx_py_Free(jx_Parser, jx__py_free);
}
#endif

static jx_status jx_py_scanner_state_init(jx_py_scanner_state *state)
{
  memset(state,0,sizeof(jx_py_scanner_state));
  state->indent_stack = jx_list_new();
  return JX_SUCCESS;
}

static jx_status jx_py_scanner_state_reset(jx_py_scanner_state *state)
{
  if(state->bot) 
    jx_free(state->bot);
  state->bot = NULL;
  state->tok = NULL;
  state->ptr = NULL;
  state->cur = NULL;
  state->pos = NULL;
  state->lim = NULL;
  state->top = NULL;
  state->eof = NULL;
  state->line = 0;
  state->n_tok_parsed = 0;
  state->current_indent = 0;
  state->colon_just_seen = JX_FALSE;
  state->newline_just_seen = JX_FALSE;
  jx_list_reset(state->indent_stack);
  return JX_SUCCESS;
}

static jx_status jx_py_scanner_state_purge(jx_py_scanner_state *state)
{
  jx_ob_free(state->indent_stack);
  /* free last object */
  jx_ob_free(state->context.result);
  /* free the input buffer (if using stdin) */
  switch(state->mode) {
  case JX_PY_SCANNER_MODE_FILE:
  case JX_PY_SCANNER_MODE_CONSOLE:
    if(state->bot) 
      jx_free(state->bot);
    break;
  }
  return JX_SUCCESS;
}

void jx_py_echo_stdin(void)
{
  jx_py_scanner_state state;
  jx_py_scanner_state_init(&state);
  jx_bool done = JX_FALSE;
  while(!done) {    
    jx_py_scan_input(&state);
    switch(state.context.status) {
    case JX_STATUS_SYNTAX_ERROR:
      printf("syntax error.\n");
      break;
    case JX_YES: /* accepted */
      {
        jx_ob jxon = jx_ob_to_jxon(state.context.result);
        if(state.n_tok_parsed)
          printf("%s;\n",jx_ob_as_str(&jxon));
        jx_ob_free(jxon);
      }
      state.context.result = jx_null_with_ob(state.context.result);
      break;
    case JX_FAILURE:
      done = JX_TRUE;
      break;
    }
    if(state.context.exhausted)
      done = JX_TRUE;
  }
  jx_py_scanner_state_purge(&state);
}

#define JX_PY_SCANNER_MAGIC "jxJSc"

typedef struct {
  jx_opaque_ob opaque;
  jx_py_scanner_state state;
} jx_py_scanner;

static jx_status jx_py_scanner_free(jx_py_scanner *scanner) 
{
  if(jx_ob_equal(scanner->opaque.magic,
                 jx_ob_from_str(JX_PY_SCANNER_MAGIC))) {
    jx_py_scanner_state_purge(&scanner->state);
    jx_ob_free(scanner->opaque.magic);
    jx_free(scanner);
    return JX_SUCCESS;
  }
  return JX_FAILURE;
}

jx_ob jx_py_scanner_new_with_file(FILE *file)
{
  jx_ob result = JX_OB_NULL;
  jx_py_scanner *scanner = (jx_py_scanner*)jx_calloc(1,sizeof(jx_py_scanner));
  if(scanner) {
    if(jx_ok(jx_py_scanner_state_init(&scanner->state))) {
      scanner->opaque.magic = jx_ob_from_str(JX_PY_SCANNER_MAGIC);
      scanner->opaque.free_fn = (jx_opaque_free_fn)jx_py_scanner_free;
      scanner->state.file = file;
      if (isatty((int)fileno(file))) {      
        scanner->state.mode = JX_PY_SCANNER_MODE_CONSOLE;
      } else {
        scanner->state.mode = JX_PY_SCANNER_MODE_FILE;
      }
      result = jx_builtin_new_with_opaque_ob(&scanner->opaque);
    } else 
      jx_free(scanner);
  }
  return result;
}

jx_ob jx_py_scanner_get_error_message(jx_ob scanner_ob)
{
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_py_scanner *scanner = (jx_py_scanner*)scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic,
                   jx_ob_from_str(JX_PY_SCANNER_MAGIC))) {
      jx_py_scanner_state *state = &scanner->state;
      jx_ob list = jx_list_new();
      {
        jx_char buffer[50];
        sprintf(buffer,"Error: invalid syntax on line %d\n",(int)state->line+1);
        jx_list_append(list, jx_ob_from_str(buffer));
      }
      if(state->bot != state->lim) {
        if(state->tok > state->pos) {
          jx_list_append(list, jx_ob_from_str_with_len(state->pos, state->tok - state->pos));
        } else if(state->tok > state->bot) {
          jx_list_append(list, jx_ob_from_str_with_len(state->bot, state->tok - state->bot));
        }
        if((state->cur > state->tok) && state->tok && state->tok[0]) {
          jx_list_append(list, jx_ob_from_str(" -->"));
          jx_list_append(list, jx_ob_from_str_with_len(state->tok, state->cur - state->tok));
          jx_list_append(list, jx_ob_from_str("<-- "));
          if(state->lim > state->cur) {
            jx_char *ch = state->cur;
            while( (ch<state->lim) && (*ch!='\n') &&(*ch!='\r'))
              ch++;
            jx_list_append(list, jx_ob_from_str_with_len(state->cur, ch - state->cur));
          }
        } else {
          jx_list_append(list, jx_ob_from_str("<-- (at end of input)"));
        }
      } else {
        jx_list_append(list, jx_ob_from_str("<-- (at end of input)"));
      }
      return jx_str_join_with_list(list);
    }
  }
  return jx_ob_from_null();
}

jx_status jx_py_scanner_next_ob(jx_ob *result, jx_ob scanner_ob)
{
  jx_status status = JX_FAILURE;
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_py_scanner *scanner = (jx_py_scanner*)scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic,
                   jx_ob_from_str(JX_PY_SCANNER_MAGIC))) {
      jx_py_scanner_state *state = &scanner->state;
      state->context.status = JX_SUCCESS;
      while(!state->context.status) {    
        jx_py_scan_input(state);
        switch(state->context.status) {
        case JX_YES: /* accept called */
          jx_ob_replace(result, state->context.result);
          state->context.result = jx_ob_from_null();
          status = state->n_tok_parsed ? JX_YES : JX_NO; /* but were any tokens parsed */
          break;
        default:
          status = state->context.status;
          break;
        }
        if(state->context.exhausted) {
          if(!status) 
            status = JX_STATUS_EXHAUSTED;
          break;
        }
      }
    }
  }
  return status;
}

jx_status jx_py_scanner_purge_input(jx_ob scanner_ob)
{
  jx_status status = JX_FAILURE;
  if(jx_builtin_opaque_ob_check(scanner_ob)) {
    jx_py_scanner *scanner = (jx_py_scanner*)scanner_ob.data.io.opaque_ob;
    if(jx_ob_equal(scanner->opaque.magic,
                   jx_ob_from_str(JX_PY_SCANNER_MAGIC))) {
      jx_py_scanner_state *state = &scanner->state;
      jx_py_scanner_state_reset(state);
      status = JX_SUCCESS;
    }
  }
  return status;
}
