#define JX_NET_ERROR                           1
#define JX_NET_NEWLINE                         2
#define JX_NET_EOI                             3
#define JX_NET_PORT                            4
#define JX_NET_EQUALS                          5
#define JX_NET_PIPE                            6
#define JX_NET_NODE                            7
#define JX_NET_COLON                           8
#define JX_NET_INDENT                          9
#define JX_NET_PASS                           10
#define JX_NET_DEDENT                         11
#define JX_NET_DOT                            12
#define JX_NET_IDENT                          13
#define JX_NET_START                          14
#define JX_NET_RUN                            15
#define JX_NET_STOP                           16
#define JX_NET_OPEN_PAR                       17
#define JX_NET_CLOSE_PAR                      18
