#define JX_NET_ERROR                           1
#define JX_NET_NEWLINE                         2
#define JX_NET_EOI                             3
#define JX_NET_PORT                            4
#define JX_NET_COMMA                           5
#define JX_NET_EQUALS                          6
#define JX_NET_PIPE                            7
#define JX_NET_NODE                            8
#define JX_NET_COLON                           9
#define JX_NET_INDENT                         10
#define JX_NET_PASS                           11
#define JX_NET_DEDENT                         12
#define JX_NET_DOT                            13
#define JX_NET_IDENT                          14
#define JX_NET_START                          15
#define JX_NET_RUN                            16
#define JX_NET_STOP                           17
#define JX_NET_OPEN_PAR                       18
#define JX_NET_CLOSE_PAR                      19
#define JX_NET_ICON                           20
#define JX_NET_FCON                           21
#define JX_NET_SCON                           22
