#define JX_JXON_ERROR                           1
#define JX_JXON_SOI                             2
#define JX_JXON_EOI                             3
#define JX_JXON_SEMICOLON                       4
#define JX_JXON_OPEN_CURLY_BRACE                5
#define JX_JXON_CLOSE_CURLY_BRACE               6
#define JX_JXON_COLON                           7
#define JX_JXON_COMMA                           8
#define JX_JXON_OPEN_RECT_BRACE                 9
#define JX_JXON_CLOSE_RECT_BRACE               10
#define JX_JXON_OPEN_PAR                       11
#define JX_JXON_CLOSE_PAR                      12
#define JX_JXON_BUILTIN                        13
#define JX_JXON_ICON                           14
#define JX_JXON_FCON                           15
#define JX_JXON_SCON                           16
#define JX_JXON_IDENT                          17
#define JX_JXON_TRUE                           18
#define JX_JXON_FALSE                          19
#define JX_JXON_NULL                           20
