#define JX_SHELL_ERROR                           1
#define JX_SHELL_EOI                             2
#define JX_SHELL_SEMICOLON                       3
#define JX_SHELL_EOL                             4
#define JX_SHELL_IDENT                           5
#define JX_SHELL_COMMA                           6
#define JX_SHELL_EQUALS                          7
#define JX_SHELL_OPEN_CURLY_BRACE                8
#define JX_SHELL_CLOSE_CURLY_BRACE               9
#define JX_SHELL_COLON                          10
#define JX_SHELL_OPEN_RECT_BRACE                11
#define JX_SHELL_CLOSE_RECT_BRACE               12
#define JX_SHELL_OPEN_PAR                       13
#define JX_SHELL_CLOSE_PAR                      14
#define JX_SHELL_BUILTIN                        15
#define JX_SHELL_ICON                           16
#define JX_SHELL_FCON                           17
#define JX_SHELL_SCON                           18
#define JX_SHELL_TRUE                           19
#define JX_SHELL_FALSE                          20
#define JX_SHELL_NULL                           21
